### ISSUE TITLE
More intuitive progress bar

### ISSUE THREAD

**Issue by justinGilmer** [glotzerlab/signac-flow#108]
### Feature description
The progress bar in `flow` should reflect the progress of each statepoint, not the total operations it has to collect and run.

### Proposed solution
The progress bar should be a function of the number of statepoints and the bar should only increment once all the labels/statuses have been checked and applied to that statepoint.

### Additional context

When showing the progress bar when running any flow command `status`, etc. on versions of `flow` >= 0.7.X, the progress bar will overflow past the # of statepoints due to label checking, etc. This is different compared to previous behavior, as the label checking appeared to be a part of the progress bar (it appeared that all the label checking was done per statepoint before incrementing the progress bar.)

I think this should be the preferred way to present this information to the user, since the progress bar loses meaning if it overflows.

This was an issue that I ran into with my systems which had a lot of labels, the progress bar would fill in a few seconds, but then it would spend an additional 10-30 seconds still counting iterations for the various labels, etc. This was quite confusing and made it difficult for me to determine what the issue was.

**Comment by csadorf** [comment]
Thx for reporting! I wasn't aware of this issue.

**Comment by vyasr** [comment]
I suspect that this is a bug I introduced with the status optimizations we merged recently.

**Comment by csadorf** [comment]
> I suspect that this is a bug I introduced with the status optimizations we merged recently.

Ok, could you investigate?
