### ISSUE TITLE
Job-operation name collisions 

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-flow#116]
### Description

I'm running into an issue where when I run `status`, a `FileNotFoundError` is being raised about bundled jobs that are in a different projects on the same filesystem. Both projects have the same name (as specified in `signac.rc`). Additionally, the names of the root directories are similar for each: one is in `/path/to/projects/depletant-assembly` and the other is in `/path/to/projects/depletant-phase-diagram`. So when `status` queries the scheduler, it thinks that there should be bundled jobs based in this project that are actually in the other project. Hence, it can't find those files in the project and throws the error. 

I was able to get things working by just changing the name of one of the projects.

### System configuration

This is on Stampede2, and I build `signac-flow` from source on commit `6af28ce56aa6ea3c89c5ff9bd5bf56dc3bb43caf` on `master`. For reference:

```bash
 $ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'
Linux-3.10.0-957.5.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
3.6.3 (default, Dec 11 2017, 21:18:04) 
[GCC Intel(R) C++ gcc 5.4 mode]
1.0.0
0.7.1
```

**Comment by vyasr** [comment]
How do we want to go forward with fixing this? Short of including the entire folder name, perhaps incorporate a hash of the folder name into the bundle id as well?

**Comment by b-butler** [comment]
@vyasr that makes sense. Including the directories base path in the hash should prevent collisions at least from my understanding of hash algorithms.

**Comment by csadorf** [comment]
I agree, we should use the hash of the root directory instead of the root directory itself, here: https://github.com/glotzerlab/signac-flow/blob/master/flow/project.py#L285

**Comment by tcmoore3** [comment]
Is `signac.contrib.hashing.calc_id()` the right way to do the hashing? 

Also, is there any specific reason for using the hash of `project.root_directory()` rather than just the root directory? [That bit gets hashed into `job_op_id` anyway](https://github.com/glotzerlab/signac-flow/blob/master/flow/project.py#L297), so unless I'm missing something there shouldn't be a need to use the hash of the root directory there.

**Comment by csadorf** [comment]
> Is `signac.contrib.hashing.calc_id()` the right way to do the hashing?

Yes, I think it's a good idea to use the same hashing algorithm across the framework, but it's not a strict requirement.

> Also, is there any specific reason for using the hash of `project.root_directory()` rather than just the root directory? [That bit gets hashed into `job_op_id` anyway](https://github.com/glotzerlab/signac-flow/blob/master/flow/project.py#L297), so unless I'm missing something there shouldn't be a need to use the hash of the root directory there.

You are correct, it doesn't make sense to hash the directory name twice.

**Comment by vyasr** [comment]
I'm confused, did we actually resolve the issue? If the root directory is already part of the hash, how did this issue arise in the first place?

**Comment by csadorf** [comment]
> I'm confused, did we actually resolve the issue? If the root directory is already part of the hash, how did this issue arise in the first place?

Noe, idea how it occurred in the first place. We can reopen if this happens again.
