### ISSUE TITLE
Proposal: make `@with_job` take a subfolder

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-flow#119]
Sometimes it's useful to create subfolders in the workspace's job folders, and managing them manually can get tricky. I therefore propose adding an optional subfolder parameter to the `with_job` decorator, and the operation would be executed in that job subfolder.

**Comment by csadorf** [comment]
@berceanu I've just linked to an existing issue (#73) that would generalize this concept even further.

**Comment by berceanu** [comment]
After much experimentation, I decided subfolders are not the best approach, and opted for sub-projects instead. As a result, my project hierarchy now looks like this:

```
├── rpa
│   ├── aggregation
│   │   ├── animation
│   │   │   ├── signac.rc
│   │   │   ├── src
│   │   │   │   ├── animation.py
│   │   │   │   └── dashboard.py
│   │   │   └── workspace
│   │   ├── signac.rc
│   │   ├── src
│   │   │   ├── aggregation.py
│   │   │   └── dashboard.py
│   │   └── workspace
│   ├── signac.rc
│   ├── src
│   │   ├── dashboard.py
│   │   ├── init.py
│   │   ├── project.py
│   └── workspace
└── talys
    ├── aggregation
    │   ├── neutron_number
    │   │   ├── signac.rc
    │   │   ├── src
    │   │   │   └── dashboard.py
    │   │   └── workspace
    │   ├── neutron_number.py
    │   ├── temperature
    │   │   ├── signac.rc
    │   │   ├── src
    │   │   │   └── dashboard.py
    │   │   └── workspace
    │   └── temperature.py
    ├── hfb_qrpa
    │   ├── signac.rc
    │   ├── src
    │   │   ├── dashboard.py
    │   │   ├── init.py
    │   │   └── project.py
    │   └── workspace
    ├── signac.rc
    ├── src
    │   ├── dashboard.py
    │   ├── init.py
    │   └── project.py
    └── workspace
```

**Comment by csadorf** [comment]
@berceanu Thank you for sharing! Do you think that makes the `@with_job` decorator less useful in that context? Or are there any other API short-cuts that might be useful?

**Comment by berceanu** [comment]
Well, in this case working with sub-projects rather than sub-folders is more intuitive, so extending `@with_job` wouldn't help I think.

**Comment by vyasr** [comment]
Closing pending further interest.
