### ISSUE TITLE
Support University of Michigan Great Lakes Cluster

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#131]
### Feature description

The University of Michigan [Great Lakes cluster](https://arc-ts.umich.edu/greatlakes/) is now in *early-testing* mode. We should run tests and develop an environment+template *if necessary* to support it.

### Proposed solution

Run unit tests and test a basic submission workflow on the Great Lakes system.

**Comment by csadorf** [comment]
Using just defaults works for simple CPU jobs. We will need a dedicated environment and template to support GPU and large-memory jobs.

**Comment by bdice** [comment]
@Tobias-Dwyer You were asking about this recently -- just wanted to make you aware that an issue exists and would be a viable hackathon project.

**Comment by vyasr** [comment]
Resolved by #185
