### ISSUE TITLE
Drop support for signac 0.9.x

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#140]
We should drop support for signac version 0.9.x.

Here is what we need to do for that:

* [x] Document all supported versions in the docs on the [installation](https://docs.signac.io/projects/flow/en/latest/installation.html) page.
* [x] Announce drop of support in the changelog.
* [x] Remove unit tests in the circle-ci config.
* [x] Update requirements in the setup.py file.
* [ ] Update requirements in the signac-flow conda recipe.

**Comment by bdice** [comment]
@csadorf I think the conda recipe will need to be updated when we make a release of v0.8.

**Comment by csadorf** [comment]
Resolved with merge of #151 .

**Comment by bdice** [comment]
Dependency updated for conda-forge: https://github.com/conda-forge/signac-flow-feedstock/pull/15
