### ISSUE TITLE
Use environment profiles on opt-out basis

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#16]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/16) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

To use the shipped environment profiles, users are currently required to *opt-in* by adding the following line to the `project.py` file: `import flow.environments`.

We do this as a pre-cautionary measure, however I think it is fair to assume that this should be the default behavior.

I propose that we switch to an *opt-out* model with 6.0, where users can opt out to use profiles by changing the signac configuration:
```
[flow]
use_shipped_environments = False
```
or by switching a global variable: `flow.USE_SHIPPED_ENVIRONMENTS = False`.

*The exact name of the variable would be up for debate.*

**Comment by bdice** [comment]
I'd like this feature, too - maybe a hackathon project.
