### ISSUE TITLE
Documentation for old flow API

### ISSUE THREAD

**Issue by rosecers** [glotzerlab/signac-flow#165]
I'm still working with flow, and working with my new group on adopting signac and flow. Many of the new group mates (and myself tbh) prefer the old API, but the documentation only includes the new API. Can you add documentation for the old API? I've gotten many requests.

Old API= class structure, separate project.py and operations.py,  self.add_operation()
New API=@FlowProject.operation()

**Comment by csadorf** [comment]
I've advocated before that the *old API* should not be deprecated and is still fully viable. @rosecers Where would you like to see the documentation?

**Comment by bdice** [comment]
This has been resolved: https://docs.signac.io/projects/flow/en/latest/api.html#flow.FlowProject.add_operation
