### ISSUE TITLE
Running on an LSF system without LSB_BJOBS_FORMAT set causes subprocess.CalledProcessError

### ISSUE THREAD

**Issue by ilumsden** [glotzerlab/signac-flow#166]
### Description

When running `signac-flow` code with `DefaultLSFEnvironment` on a platform where the LSF environment variable `LSB_BJOBS_FORMAT` is not set, a `subprocess.CalledProcessError` is raised in [the `_fetch` function in `lsf.py`](https://github.com/glotzerlab/signac-flow/blob/1f1e11ce2fb298a7fe0fd6af2ee3a742ede72607/flow/scheduling/lsf.py#L43). This is because the command passed to `check_output` does not include the `-o` flag. From [IBM's documentation](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_command_ref/bjobs.json.1.html), the `-json` flag can only be used when either:
1. the `-o` flag is set (which is currently not the case in `signac-flow`)
2. the `LSB_BJOBS_FORMAT` LSF environment variable is set
On platforms where this environment variable is not set (like the new POWER9 cluster I'm using), the omission of the `-o` flag causes the `bjobs` command to fail.

### To reproduce

Run any `signac-flow` code with `DefaultLSFEnvironment` on a platform where the LSF environment variable `LSB_BJOBS_FORMAT` is __not__ set.

### Error output

```
bjobs: You cannot use the -json option when the -o option is not specified or the LSB_BJOBS_FORMAT parameter is not defined.

bjobs

Displays and filters information about LSF jobs. Specify one or more job
IDs (and, optionally, an array index list) to display information about
specific jobs (and job arrays).

Synopsis
       bjobs [options] [job_ID | "job_ID[index_list]" ... ]

       bjobs -h[elp] [all] [description] [category_name ...]
       [-option_name ...]

       bjobs -V

Categories and options
       Use the keyword all to display all options and the keyword
       description to display a detailed description of the bjobs com-
       mand. For more details on specific categories and options, spec-
       ify bjobs -h with the name of the categories and options.

	  Category: filter
	  Filter specific types of jobs: -A, -aff, -app, -aps, -data,
	  -fwd, -g, -G, -J, -Jd, -Lp, -m, -N, -P, -plan, -prio, -psum,
	  -q, -rusage, -sla, -ss, -u.

	  Category: format
	  Control the bjobs display format: -aff, -cname, -hostfile, -l,
	  -N, -noheader, -o, -psum, -sum, -UF, -w, -W, -WF, -WL, -WP,
	  -X.

	  Category: state
	  Display specific job states: -a, -d, -N, -p, -pe, -pei, -pi,
	  -psum, -r, -s, -sum, -x.

bjobs.main(1)							 bjobs.main(1)

			       Category: filter

       Filter specific types of jobs: -A, -aff, -app, -aps, -data, -fwd,
       -g, -G, -J, -Jd, -Lp, -m, -N, -P, -plan, -prio, -psum, -q,
       -rusage, -sla, -ss, -u.

       Parent topic: bjobs

       Parent topic: Categories

bjobs.main(1)							 bjobs.main(1)

			       Category: format

       Control the bjobs display format: -aff, -cname, -hostfile, -l,
       -N, -noheader, -o, -psum, -sum, -UF, -w, -W, -WF, -WL, -WP, -X.

       Parent topic: bjobs

       Parent topic: Categories

bjobs.main(1)							 bjobs.main(1)

				Category: state

       Display specific job states: -a, -d, -N, -p, -pe, -pei, -pi,
       -psum, -r, -s, -sum, -x.

       Parent topic: bjobs

       Parent topic: Categories

ERROR: Encountered error during program execution: 'Command '['bjobs', '-json', '-u', 'ilumsden']' returned non-zero exit status 255.'
Execute with '--show-traceback' or '--debug' to get more information.
```

### System configuration

Please complete the following information:

 - Operating System: RedHat 7.6 (POWER9), Linux Kernel 4.14.0
 - Version of Python: Python 3.7.3
 - Version of signac: 1.2.0
 - Version of signac-flow: 0.8.0

**Comment by ilumsden** [comment]
I should also mention that, after reviewing this repo's code, I found that the only info needed from `bjobs` is `jobid`, `stat`, and `job_name`.

**Comment by ilumsden** [comment]
I just finished implementing a fix for this on [my personal fork](https://github.com/ilumsden/signac-flow/blob/6d03ef81a098126eb61116d2fc690132de739f42/flow/scheduling/lsf.py#L43). I tested it using the workflow that I've been working with. If you'd like it to be added, just let me know, and I'll make a PR.

**Comment by csadorf** [comment]
@ilumsden Great! We would very much appreciate if you could create a PR. Make sure to review the [contributing guidelines](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md), thank you!

**Comment by vyasr** [comment]
@ilumsden did you get a version of this to work on your fork? If so, would you like to contribute it back to our package? We always appreciate PRs!

**Comment by bdice** [comment]
@ilumsden Could you make a PR with your fix? Thanks!

**Comment by vyasr** [comment]
According to the forked version, this issue can be fixed by changing the `cmd` in `lsf.py::_fetch` to include `'-o', 'jobid stat user job_name'` so that the relevant data will always be written (whether or not `LSB_BJOBS_FORMAT`) is set. I'm documenting here, but not making a PR right now since it will require testing on a system using an LSF scheduler.

**Comment by csadorf** [comment]
@vyasr Should we close this issue?

**Comment by vyasr** [comment]
Ideally we should fix this, and the fix appears trivial, but without an LSF system to test on where the current version fails (Summit sets the relevant environment variable for us, and that's our only LSF machine) I don't think we'll know that it worked. Our options are either 1) close this issue, or 2) make this change and verify that it doesn't break on Summit. I'd be fine with either option; if we can confirm that (2) doesn't break our Summit usage, I don't see any harm in making the change preemptively. That would require someone who's actually running on Summit actively to test though. @bdice or @klywang, would either of you be able to test this out? If not, we can close.

**Comment by csadorf** [comment]
One option might be to install the LSF scheduler on a Ubuntu host (e.g. vagrant virtual box) following these instructions: https://www.ibm.com/support/knowledgecenter/SSZUDP_10.2.0/suite_install/lsf_suite_install_ubuntu.html

**Comment by vyasr** [comment]
Yes, that would work, but probably is more work than it's worth at the moment. I think that this is very low priority for us since nobody is actively running into this issue, so I'll close this for now. The proposed fix is documented in one of my comments above, if someone else runs into this problem we can reopen and suggest that they implement and test the fix.
