### ISSUE TITLE
show_traceback = on by default

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#169]
### Feature description

Related to #61 and #144, I think it would be good if `show_traceback = on` by default.

### Proposed solution

Change default behavior to enable traceback.

@glotzerlab/signac-developers What are your thoughts about this potential change? The tracebacks are sometimes a little complicated, but I think it's reasonable to expect that Python scripts will show a traceback on error.

**Comment by tommy-waltmann** [comment]
What extra information would the show_traceback option display that the script wouldn't?

**Comment by bdice** [comment]
@tommy-waltmann Here's a simple example. This operation raises an error:

```python
from flow import FlowProject


class Project(FlowProject):
    pass


@Project.operation
def raise_error(job):
    raise RuntimeError('woop woop woop error!')


if __name__ == '__main__':
    Project().main()
```

If you execute this project in a non-empty signac project folder, you get the following output:

```bash
user@host ~/tmp_signac $ python3 project.py run
Using environment configuration: UnknownEnvironment
ERROR: Encountered error during program execution: 'woop woop woop error!'
Execute with '--show-traceback' or '--debug' to get more information.
```

Running with `--show-traceback` shows the following output which is much more verbose, but gives a full traceback of how the error occurred:
```bash
user@HOST ~/tmp_signac $ python3 project.py run --show-traceback
Using environment configuration: UnknownEnvironment
ERROR: Encountered error during program execution: 'woop woop woop error!'
Execute with '--show-traceback' or '--debug' to get more information.
Traceback (most recent call last):
  File "project.py", line 15, in <module>
    Project().main()
  File "/home/bdice/code/signac-flow/flow/project.py", line 2890, in main
    _exit_or_raise()
  File "/home/bdice/code/signac-flow/flow/project.py", line 2858, in main
    args.func(args)
  File "/home/bdice/code/signac-flow/flow/project.py", line 2564, in _main_run
    run()
  File "/home/bdice/code/signac-flow/flow/project.py", line 1720, in run
    np=np, timeout=timeout, progress=progress)
  File "/home/bdice/code/signac-flow/flow/project.py", line 1462, in run_operations
    self._execute_operation(operation, timeout)
  File "/home/bdice/code/signac-flow/flow/project.py", line 1549, in _execute_operation
    self._operation_functions[operation.name](operation.job)
  File "project.py", line 11, in raise_error
    raise RuntimeError('woop woop woop error!')
RuntimeError: woop woop woop error!
```

With this information, I can identify exactly what went wrong (my project raised an error on line 11). Otherwise it can be very tricky to diagnose issues with code in the project. With a long-running operation it is _especially_ annoying, because running again with `--show-traceback` may take several minutes.

**Comment by csadorf** [comment]
I would like to propose a compromise. The majority of signac users appear to use the command line tools as primary entry points. It is reasonable to expect that these entrypoints do not present full tracebacks as the *default* error feedback. I consider myself a Python expert user and am usually thrown off by tools (implemented in Python) that do not shield me from a full traceback for "expected failure scenarios" as the primary error mechanism.

Instead I propose to show a truncated traceback and **ask** the user whether they would like to see the full traceback. Something like this:
```
user@host ~/tmp_signac $ python3 project.py run
Using environment configuration: UnknownEnvironment
ERROR: Encountered error during execution of operation "foo": 
----
Traceback (most recent call):
[ omitted ]
  File "project.py", line 11, in raise_error
    raise RuntimeError('woop woop woop error!')
RuntimeError: woop woop woop error!
----
Do you want to see the full traceback? [y/N]
```

**Comment by bdice** [comment]
@csadorf Good concept. I tried a different approach, which truncate the traceback to only show the user-side portion of the traceback and hide the signac-flow portions. I used the `traceback` module for this. I think it's a pretty robust solution that conceals the `project.py` entry point's stack. Another side-effect (which I _think_ is desirable) is that it put the `ERROR` at the bottom instead of the top.

```python
user@HOST ~/tmp_signac $ python project.py run
Using environment configuration: UnknownEnvironment
Traceback (most recent call last):
  File "/home/bdice/code/signac-flow/flow/project.py", line 1554, in _execute_operation
    self._operation_functions[operation.name](operation.job)
  File "project2.py", line 10, in raise_error
    raise RuntimeError('woop woop woop error!')
RuntimeError: woop woop woop error!
ERROR: Encountered error during program execution: 'woop woop woop error!'
Execute with '--show-traceback' or '--debug' to get more information.
```

**Comment by csadorf** [comment]
Ok, I think that's an improvement, however I would still prefer a better encapsulation of the traceback within the error feedback.

What do you think of the question prompt? Could be very easily implemented with click.

**Comment by bdice** [comment]
@csadorf I don't particularly like adding an interactive component for long-running processes. I frequently "set and forget" runs like these.

**Comment by csadorf** [comment]
What's the concern? That the process does not terminate?

**Comment by tommy-waltmann** [comment]
I like the truncated traceback option, the user can quickly find the location of their error, but at the same time isn't too verbose. We should also have a way for the user to get the full traceback if they want it.

**Comment by bdice** [comment]
@csadorf I think it’s unusual and non-UNIXy to require user input in a place like this. Cases like `python project.py run > run.log` get messy.

@tommy-waltmann I mostly agree. We can narrow the relevant part of the traceback to the user code with certainty, so the option for a “full traceback” (including signac-flow’s internal run logic) would be a tradeoff for me with configuration complexity (if the user doesn’t care about flow’s internal logic, that can be ignored without needing to add even more config options that we must maintain). Personally, I would only ever give the truncated traceback. Flow developers _might_ want more, but it’s probably clear enough from the one line in the truncated traceback that gives the function call from flow.

**Comment by csadorf** [comment]
> @csadorf I think it’s unusual and non-UNIXy to require user input in a place like this. Cases like `python project.py run > run.log` get messy. I don’t think we require user input anywhere else in our command line entry points.

I was honestly under the assumption that `click` would handle your piping example just fine, but a quick test shows that it doesn't. So, I'm ok with dropping that idea.

However, I think it's important to have an option to show the full traceback **including** the signac-flow code. I think that should at least the behavior in combination with `--debug`.

How about this:
* _no options_: show **minimal** traceback, user code only
* `--show-traceback` / config option set: show full user-code traceback
* `--debug`: Show **full** traceback

**Comment by csadorf** [comment]
Addendum: We could test indenting the quoted traceback to make it immediately visually distinct from a normal Python traceback.

**Comment by tommy-waltmann** [comment]
I agree with Simon's suggestion, perhaps we could also change the option "--show-traceback" to "--full-traceback" (or something like that), since it would by default give some of the user's traceback now. This may be annoying to do, however, because of having to globally search and replace the variable (I'm not familiar with implementation).

**Comment by bdice** [comment]
This issue is resolved by #171, which always shows the user portion of the traceback. If you want the full traceback including the traceback from signac-flow, users can run with `--show-traceback`.

**Comment by joaander** [comment]
*Users* write their `project.py` files. This decision to hide tracebacks from user code has resulted in many hours of frustration for users attempting to debug issues in the scripts they wrote. Novice users don't realize that they need to pass "--show-traceback" and provide the full output when asking for support. Users of singularity containers are expected to know that they also need to create [debug groups that shadow their operations](https://docs.signac.io/en/latest/recipes.html#passing-command-line-options-to-operations-run-in-a-container-or-other-environment) in order to get traceback information from their code.  (note, that example is missing `submit_options="--debug"`).

It would be better if the user was given full information on errors by default and they can choose to hide that information if they do not wish to see it. This will save countless hours of troubleshooting as users will be able to provide complete information in their first request for support. For example:
```
Traceback (most recent call last):
  File "/jet/home/joaander/venv/lib/python3.8/site-packages/flow/project.py", line 5117, in main                                     
    args.func(args)
  File "/jet/home/joaander/venv/lib/python3.8/site-packages/flow/project.py", line 4834, in _main_exec                               
    operation_function(*aggregate)
  File "/jet/home/joaander/venv/lib/python3.8/site-packages/flow/project.py", line 630, in __call__                                  
    return self._op_func(*jobs)
  File "/ocean/projects/dmr170059p/joaander/hoomd-validation/hoomd_validation/lj_fluid.py", line 129, in run_nvt_md_sim              
    import hoomd
  File "/jet/home/joaander/venv/lib/python3.8/site-packages/hoomd/__init__.py", line 13, in <module>                                 
    from hoomd import version
  File "/jet/home/joaander/venv/lib/python3.8/site-packages/hoomd/version.py", line 36, in <module>                                  
    from hoomd import _hoomd
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory    
```
instead of just:
```
ERROR: Encountered error during program execution: 'libcudart.so.11.0: cannot open shared object file: No such file or directory'
```

**Comment by bdice** [comment]
@joaander I am not exactly sure what is going wrong here, but I would have expected that error to show up in the traceback without additional effort. Do you need `--show-traceback` or both `--show-traceback --debug` to get the error output you expect? Or is it something specific to running in a container?

**Comment by joaander** [comment]
As documented here: https://docs.signac.io/en/latest/recipes.html#passing-command-line-options-to-operations-run-in-a-container-or-other-environment
Neither `--show-traceback` nor `--debug` passed on the command line (`python project.py submit --debug`) are passed to the corresponding signac-flow command line inside the container:
```

For example:
```
$ python hoomd_validation/lj_fluid.py submit -o run_nvt_md_sim -n 1 --debug --pretend
Using environment configuration: Bridges2Environment
DEBUG:flow.project:Entering buffered mode.
Querying scheduler...
DEBUG:flow.project:Exiting buffered mode.
DEBUG:flow.project:Entering buffered mode.
Submitting cluster job 'LJFluid/86c08136e06ad5b02ff1bb871616dfff/run_nvt_md_s/a0892392abc892f561b517cbc81f7c4e':
INFO:flow.project:Set 'base_script=bridges2.sh'.
INFO:flow.project:Use environment '<class 'flow.environments.xsede.Bridges2Environment'>'.
 - Group: run_nvt_md_sim(86c08136e06ad5b02ff1bb871616dfff)
# Submit command: sbatch
#!/bin/bash
#SBATCH --job-name="LJFluid/86c08136e06ad5b02ff1bb871616dfff/run_nvt_md_s/a0892392abc892f561b517cbc81f7c4e"
#SBATCH --partition=RM-shared
#SBATCH -t 48:00:00
#SBATCH -N 1
#SBATCH --ntasks=1

set -e
set -u

cd /ocean/projects/dmr170059p/joaander/hoomd-validation/LJFluid

module load openmpi/4.0.5-gcc10.2.0

# run_nvt_md_sim(86c08136e06ad5b02ff1bb871616dfff)
/jet/home/joaander/venv/bin/python /ocean/projects/dmr170059p/joaander/hoomd-validation/hoomd_validation/lj_fluid.py run -o run_nvt_md_sim -j 86c08136e06ad5b02ff1bb871616dfff
# Eligible to run:
# mpirun -n 1  singularity exec --bind /ocean /ocean/projects/dmr170059p/joaander/hoomd-validation/software.sif /opt/glotzerlab/bin/python /ocean/projects/dmr170059p/joaander/hoomd-validation/hoomd_validation/lj_fluid.py exec run_nvt_md_sim 86c08136e06ad5b02ff1bb871616dfff
```
Note that lack of the `--debug` option in the `Eligible to run` section of the output. Users must take extra steps to see tracebacks that result in their code.

**Comment by b-butler** [comment]
To provide clarification the `show-traceback` option in the config file works as anticipated, but is not set to `true` by default and is not very visible to the user (as our whole config is in general).

My thoughts on the above discussion -- hopefully they contribute meaningfully -- are that the signac-flow CLI is different from the signac CLI and most other CLI's. To even use `./project.py ...` users _must write_ a project.py file. For command line applications like black, they do not need to show tracebacks because the user should not be able to make the code error unexpectedly (this would be a bug). However, for flow `project.py` for most users will have some error(s), usually multiple, in the process of creating and modifying a workflow. This _requirement_ of code completely changes the nature of CLI expectations. It is more akin to a user writing a Python script using a Python library than using a CLI, and thus the difficultly in geting traceback information (by default) is irritating to users and the wrong decision.

**Comment by csadorf** [comment]
@b-butler Well put. I'm convinced, the traceback should be shown by default.

**Comment by bdice** [comment]
I’d support a PR for changing this, as well.
