### ISSUE TITLE
Deprecate flow.run

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#221]
### Issue

The `flow.run` interface (which supports operations modules, like `operations.py`) should be deprecated. This is no longer useful and it is straightforward to convert an operations module into a FlowProject. https://docs.signac.io/projects/flow/en/latest/api.html#flow-run

### Proposed solution

Deprecate `flow.run`.

**Comment by rosecers** [comment]
I *strongly* disagree. I like to keep my operations and project flow in separate files. It also encourages users to retain old code.

**Comment by bdice** [comment]
@rosecers You can still keep operations and project flow (e.g. pre/postconditions) in separate files and import them. How do you use `flow.run()`? Are there use cases that the FlowProject is not serving?

On the “old code” front, we often strive for some backwards compatibility during a deprecation cycle but remember that signac-flow is unstable. I don’t think that this feature belongs in a stable (1.0) release unless it provides functionality not covered by the FlowProject.

Since this seems controversial, I will remove the “good first issue” label. I discussed this with @vyasr offline before making this issue. @glotzerlab/signac-committers, maybe another opinion would be helpful here.

**Comment by csadorf** [comment]
First of, while we are currently not advertising this function as best practice to users, I do not think that the specific function of `flow.run()` (providing a simple interface to directly execute top-level functions from the command line) is *directly* covered by the `FlowProject` class. One could argue that creating libraries consisting of multiple modules of functions is easier with `flow.run()` compared to combining multiple `FlowProject` classes.

I also do not see any major maintenance burden imposed by keeping that function in the package. IMO, the cost for breaking existing functional workflows appears to outweigh the cost for maintaining this specific function.

I think that we have to be very careful with the argument that *signac-flow* is unstable. While technically true and this classification provides us with a baseline of necessary flexibility, the package has been around long enough and is foundation for sufficiently many production workflows that any specific deprecation needs to have sufficient justification in terms of the technical debt imposed through prolonged maintenance.

Unless a strong argument can be made as to how maintaining this function poses a major burden or blocks us from moving forward with the implementation of other features in the package, I do not see a clear indication for deprecating or removing this function.

**Comment by bdice** [comment]
For context, this issue came up because of new user confusion. @cbkerr inherited some scripts from an older project (which I think didn’t run without modifications anyway). I didn’t want to promote confusion over best practices, when the FlowProject seems to be a superior solution to me and we have pushed users to adopt FlowProjects for as long as I can remember being involved with signac. I think that your argument is fine, @csadorf, and I will close this issue for now since I see no clear action to be taken. It may be worth revisiting before we choose to make the API stable.
