### ISSUE TITLE
Executable directive causes issues with groups branch

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#223]
### Description

I'm using containers on Bridges AI. I set the directives to include `executable='singularity exec --nv /path/to/container.simg python'`.

Then my submission scripts looks like `singularity exec --nv /path/to/container.simg python /path/to/project.py run -o operation -j job`. However, when the container tries to execute `run`, it seems to obey the directives again and tries to launch singularity! It looks like it's trying to run `singularity exec container.simg python project.py exec operation job` from inside the container...

### To reproduce

Here's something close to a minimal working example, which should be close enough to understand the problem:
```python
import flow
from flow import FlowProject

class Project(FlowProject):
    pass

img = '/pylon5/mr562bp/bdice/19.11-tf2-py3-glotzer.simg'

@Project.operation
@flow.directives(executable='singularity exec --nv {img} python'.format(img=img),
                 ngpu=1, np=4)
def train_ml(job):
    pass
```

### Error output

```python
Usage example: change_mofed_version.sh 4.5-1.0.1
2020-01-22 00:02:25.056852: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
/bin/dash: 1: singularity: not found
Using environment configuration: BridgesEnvironment
ERROR: Encountered error during program execution: 'Command 'singularity exec --nv /pylon5/mr562bp/bdice/19.11-tf2-py3-glotzer.simg python /home/bdice/code/photonics-ml/photonics_ml/project_models.py exec train_ml b75fcd800b5f3a6b0bca8add17f7b662' returned non-zero exit status 127.'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flow/project.py", line 3011, in main
    args.func(args)
  File "/usr/local/lib/python3.6/dist-packages/flow/project.py", line 2714, in _main_run
    run()
  File "/usr/local/lib/python3.6/dist-packages/flow/project.py", line 1872, in run
    np=np, timeout=timeout, progress=progress)
  File "/usr/local/lib/python3.6/dist-packages/flow/project.py", line 1611, in run_operations
    self._execute_operation(operation, timeout)
  File "/usr/local/lib/python3.6/dist-packages/flow/project.py", line 1692, in _execute_operation
    subprocess.run(operation.cmd, shell=True, timeout=timeout, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'singularity exec --nv /pylon5/mr562bp/bdice/19.11-tf2-py3-glotzer.simg python /home/bdice/code/photonics-ml/photonics_ml/project_models.py exec train_ml b75fcd800b5f3a6b0bca8add17f7b662' returned non-zero exit status 127.
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux
 - Version of Python [e.g. 3.7]: 3.6
 - Version of signac [e.g. 1.0]: 1.3
 - Version of signac-flow: 0.9, `groups` branch

@b-butler @vyasr @zhou-pj I'd appreciate your thoughts on this.

**Comment by bdice** [comment]
I'm guessing the problem is caused here: https://github.com/glotzerlab/signac-flow/blob/b6721c5f12ac5c70807213c689b2d16c92be25dc/flow/project.py#L563-L571

I think I want to use the singularity container for the "run" entry point but not the "exec" entry point. Or vice versa? I'm not sure.

**Comment by bdice** [comment]
Maybe the container also needs to be using the `groups` branch? Is this the source of the problem?

**Comment by bdice** [comment]
For now, I can dodge the problem by removing the container executable directive if the FlowProject is already running in a container. I detect the container with `SINGULARITY_NAME in os.environ`.

**Comment by b-butler** [comment]
@bdice without studying the particular issue too much, I believe what is happening is that you submit the job in `run` mode which uses `FlowProject.run`; then when you actually run the group in the container, the singleton group is still using the executable directive in `FlowProject.run`. To fix this for now, you can use `--exec` for singleton group submission which will avoid this attempt to use the container in the container.

As for what to do about this problem in general, I will need to think on it. We may need a hierarchy of directives where groups host directives for itself (In this case don't use the container) and a dictionary of directives for each of its operations (each of which might or might not use the container).

**Comment by b-butler** [comment]
Ultimately the issue, I believe, is that directives are being used twice in submission and upon execution which in this case leads to failure. I am guessing that nested singularity commands are generally no good.

**Comment by bdice** [comment]
@b-butler Yes, your understanding of the problem is correct. I was not aware of the `--exec` option. Another consideration is whether changes in flow will require updated containers — the versions inside and outside the container may differ until this has been released and the containers are updated.

**Comment by b-butler** [comment]
@bdice With groups, it would be possible to have differing versions on containers; however, it would be fragile (run not respecting directives, this issue, etc.). For instance, solutions to this issue which I can think of would require new functionality not present in signac which can't be hidden away nicely.

**Comment by bdice** [comment]
@b-butler We probably don’t need to make any guarantees about behavior with different versions inside/outside containers before 1.0, if ever. I’m mostly considering that we should _test_ this release with (and within) containers because of this problem.

**Comment by b-butler** [comment]
@bdice Ah, that, I think, is a good idea.

**Comment by vyasr** [comment]
@bdice @b-butler was the takeaway from this discussion that we shouldn't make any promises about using containers within containers, but that otherwise the executable directive is fine?

**Comment by bdice** [comment]
I think @b-butler fixed the bug on the groups branch. There are probably some ways we could improve testing, but I am going to close this issue since the original problem was resolved.
