### ISSUE TITLE
Adopt the pytest library for testing

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#227]
### Feature description

We would like to adopt `pytest` for testing in signac-flow.

See this related issue from signac for more information: https://github.com/glotzerlab/signac/issues/212
This PR to signac adopted `pytest` for testing that package: https://github.com/glotzerlab/signac/pull/275

### Proposed solution

These are the steps we would need to take:
1. [x] Updates the dev-requirements to include pytest.
2. [x] Update the circle-ci test commands.
3. [x] Update the documentation on how to run tests.
4. [x] (*optional*) Use [unittest2pytest](https://pypi.org/project/unittest2pytest/) to rewrite existing tests.

**Comment by kidrahahjo** [comment]
I'd like to work on this feature. Can you assign me this?

**Comment by bdice** [comment]
Resolved by #232.
