### ISSUE TITLE
Documenting the testing procedure

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#234]
### Feature description
It would be nice if it was easier for every beginner to see how the tests directory exactly works when we write pytest tests/.
I spent a valuable, but a large amount of time studying Signac documentation and workflow. 

### Proposed solution

Do read the complete documentation on [Signac's website](https://docs.signac.io/en/latest/) 
To make it easier for every beginner to start knowing the code without going through the complete documentation at first, I propose writing documentation after I'm done adapting pytests as a testing framework

**Comment by vyasr** [comment]
@kidrahahjo could you be a little more specific on what information you would like included? For example, are you just trying to understand what code actually gets run when you write `pytest`? If so, I think that is largely documented by pytest itself.

**Comment by kidrahahjo** [comment]
@vyasr 
Sorry for the late reply, I missed out on the comment's notification.

At that instant, I thought that beginners generally don't go through complete code before running the tests. So if we document the tests then beginners might be able to understand how the code actually works, resulting in a fast understanding of the complete flow.

I'm not quite sure that we desperately need it or not or instead do we really need it or not.

**Comment by bdice** [comment]
@kidrahahjo Do you think there is an action that we should take on this issue? If not, let's close it.

**Comment by bdice** [comment]
Here's the info we have on testing now: https://docs.signac.io/projects/flow/en/latest/support.html#testing

**Comment by kidrahahjo** [comment]
I think we should probably close it!
