### ISSUE TITLE
run command does not show command prefix

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#236]
### Description
Since the command prefix for a `JobOperation` is not generated until `flow.FlowProject._execute_operation`, when the `pretend` flag is set, there is no indication of the prefix. This could lead to confusion about the actual command being executed. In particular, MPI and OpenMP based prefixes would not be shown in pretend output.

### To reproduce

````
from flow import FlowProject, directives

@FlowProject.operation
@directives(nranks=4)
def a(job):
    pass

if __name__ == '__main__':
    FlowProject().main()
````

On command line,
````
$ python project.py run -o a --pretend
````

### System configuration

 - Version of signac [e.g. 1.0]: 1.1.0
 - Version of signac-flow: 0.9.0

**Comment by vishav1771** [comment]
@b-butler I would like to work on this issue.

**Comment by vyasr** [comment]
@b-butler what is the proposed solution for this issue?

**Comment by b-butler** [comment]
@vishav1771 @vyasr  we could perform the logic to prepend the operations' commands in `run_operations` where the `pretend` flag is checked.  In addition, we could simply move the prefix generation logic into the conditional when `pretend == True`. If we do the first, we have to make sure to only prepend those that need it, since we allow for ill formed commands to work if we don't fork. I think the first prevents code duplication and should be preferred.
