### ISSUE TITLE
Walltime should be a directive

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#240]
### Feature description

The amount of time an operation should be submitted for should be part of the recognized directives dictionary, rather than an additional command line option.

### Proposed solution

Update the directives parsing in the `FlowProject` to handle walltime directives.

**Comment by kidrahahjo** [comment]
i'd like to work on this issue

**Comment by csadorf** [comment]
@kidrahahjo Do you have any experience in working scheduling systems such as TORQUE or SLURM?

**Comment by kidrahahjo** [comment]
> @kidrahahjo Do you have any experience in working scheduling systems such as TORQUE or SLURM?

@csadorf  
I've never tried, but enthusiastic to learn about it and I've started learning too

**Comment by csadorf** [comment]
I appreciate your enthusiasm, however these scheduling systems are typically installed on supercomputing clusters and it is very difficult to learn these without having access to those. So, unless that is the case, I'd recommend to maybe take on a different task for now. I believe it will be difficult to fully understand the issue and work out a sensible solution without that background.

**Comment by kidrahahjo** [comment]
Okay no problem I'll look for a different issue to solve then.

**Comment by kidrahahjo** [comment]
I think this should get closed after we merge #283 as it includes a `WALLTIME` directive.

**Comment by kidrahahjo** [comment]
@bdice I think we should close this issue now, what do you think?

**Comment by vyasr** [comment]
Yes I think this is good to go.

**Comment by kidrahahjo** [comment]
I realised in #466 that it's not implemented yet. The `_WALLTIME` directive exists in `directives.py` but its not actually used. 
I'll take this opportunity to add this feature.
