### ISSUE TITLE
Fail gracefully when operations are used as preconditions

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#248]
### Feature description

Currently both using operations as the argument to `FlowProject.pre` and using non-operations as arguments to `FlowProject.pre.after` throw no errors, but simply silently function as no-ops. This behavior can confuse users who don't know why the conditions apparently are not obeyed. We should provide useful errors to users who try to do this.

### Proposed solution

Since operations are stored in the `FlowProject` in a list, we could check this list when preconditions are created (it may have to be done when they're collected) to ensure that the functions provided to the different types of decorators are appropriate.

**Comment by ac-optimus** [comment]
hi, can I work on this issue?

**Comment by vyasr** [comment]
Sure!
