### ISSUE TITLE
Stampede failure on parallel submission with bundling

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#250]
### Description

Due to submission scripts always using run in the groups branch, Stampede job submissions where bundling is used will fail. There is currently no way for signac to share process information to another process, so offsets can't be known within each call to `flow.run`.

### To reproduce

Bundle jobs and submit to Stampede.

### Fix
@bdice, @vyasr, and I have talked about using something like,
````python
FLOW_STAMPEDE_OFFSET=4 path/to/executable project.py run -o group -j job
FLOW_STAMPEDE_OFFSET=8 path/to/executable project.py run -o group -j job
````
and giving the Stampede environment the logic necessary to look to the environmental variable.

**Comment by vyasr** [comment]
Resolved by #298.
