### ISSUE TITLE
Execute run with pretend in template testing

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#252]
With the addition of groups, template testing is no longer as useful because all the scripts just use `python project.py run...`, which prevents us from verifying that the `mpirun`, `OMP_NUM_THREADS` and other command prefixes are correctly handled. We should add a `project.run(..., pretend=True)` called to the template test output so that we can test this behavior in the future.

**Comment by kidrahahjo** [comment]
@vyasr I'd like to work on this issue. Can you please assign me this?

**Comment by vyasr** [comment]
Hi Hardik, I'm glad you're interested in working on this issue. Unfortunately, a significant component of this issue will be manually verifying the output of our job submission process. I'm triaging a lot of issues right now and will let you know as soon as I find one that would be appropriate for you to tackle.
