### ISSUE TITLE
add_operation needed to use FlowCmdOperation instead of FlowOperation

### ISSUE THREAD

**Issue by alacour** [glotzerlab/signac-flow#254]
### Description

On great-lakes I produced an error when trying to run an operation using the Master branch of Signac. It appeared related to the add_operation command calling FlowOperation instead of FlowCmdOperation. I changed this and fixed the operation_directives to be a dict on a new branch, and am about to submit a pull request.

### Error output

File "/home/alacour/code/signac-flow/flow/project.py", line 2982, in add_operation
    op = self.operations[name] = FlowOperation(cmd=cmd, pre=pre, post=post)
TypeError: __init__() got an unexpected keyword argument 'cmd'

### System configuration

Please complete the following information:

 - Linux
 - Python 3.7:
 - Signac version: Master
 - Signac-Flow version: Master

**Comment by kidrahahjo** [comment]
@alacour Can you please give a brief overview on how to reproduce this error so that I can start working on this issue if assigned to me.

**Comment by bdice** [comment]
@kidrahahjo There is a pull request already in progress: https://github.com/glotzerlab/signac-flow/pull/255

**Comment by kidrahahjo** [comment]
@bdice Okay, thank you.
