### ISSUE TITLE
Handle job memory requests via directives

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#258]
### Feature description

While working with @jdice on #256 and #257, I considered whether our memory usage requests should be handled with directives. I think this would be a good use case for directives.

### Proposed solution

Add a directive `@directives(memory='4g')` or similar. It may need to parse strings like `1024m` or `4g` and do its math in terms of gigabytes, or we could always assume units of gigabytes and only accept numeric inputs.

### Additional context

Currently memory requests are handled inconsistently across clusters/schedulers - SLURM's handling is improved by #256 and #257 but TORQUE/LSF needs to be made consistent at some point.

**Comment by bdice** [comment]
Also memory requests are almost totally undocumented.

**Comment by vyasr** [comment]
I agree. I think almost every command line option for submission (walltime, memory, etc) should become a directive. The only possible exception is partition since I don't know if there's any way to make that portable, but we can at least aim to improve our automatic partition detection.

**Comment by kidrahahjo** [comment]
@vyasr @bdice I see that in the `GreatLakesEnvironment`, we support an argument `--memory`. I see that [SLURM](https://github.com/glotzerlab/signac-flow/blob/master/flow/templates/slurm.sh#L8) and [TORQUE](https://github.com/glotzerlab/signac-flow/blob/master/flow/templates/torque.sh#L10) use similar blocks to assign memory (I couldn't find the `memory` assignments in other templates). Is this what we wanted to remove and eventually ask users to use the directives path instead?

Apart from this, I did not find the use of [`_MEMORY`](https://github.com/glotzerlab/signac-flow/blob/master/flow/directives.py#L380) directive anywhere in `flow`.

I am happy to work on this issue but I'll be needing some guidance to start the process!

**Comment by bdice** [comment]
Yes, exactly. We would like to remove the "special" option `--memory` from specific templates and instead make it work for all schedulers. This will require us to read the documentation for SLURM, TORQUE, and LSF and determine the correct command for each template. Then we will need to add a directive that specifies the unit (gigabytes) and how the memory should be aggregated (it should be like `np`, where the requested memory is the max of the operations in serial and the sum in parallel). This could be a good office hours task.

**Comment by vyasr** [comment]
Just to clarify, the `_MEMORY` directive already exists and is documented as gigabytes. It's just a manner of removing the `--memory` options and making sure existing templates respect the directive. It would also be good to verify that all schedulers support fractional values in case users ever need to request memory in megabytes.
