### ISSUE TITLE
Remove Duplicate Directives Logic in FlowGroup and JobOperation

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#259]
### Description
The logic for aggregating directives in `FlowGroup`s has superseded the logic in `JobOperation.__init__`; however, that logic still exists. We should remove this and ensure that `FlowGroup`'s methods for creating `JobOperation`s deals with this correctly.

### Proposed solution
Looking at the logic in `JobOperation.__init__` and ensuring that all the functionality exists in `FlowGroup._create_run_job_operations` and `FlowGroup._create_submit_job_operations`, before deleting the directives logic in `JobOperation.__init__`. The one exception to this is that the logic for converting directives into a `TrackGetItemDict` should remain in `JobOperation`.

**Comment by michiboo** [comment]
Hi I am student looking to apply GSOC with signac and would like to work on this issue if possible!

**Comment by b-butler** [comment]
@michiboo, we are happy to have you help with this issue.

**Comment by vyasr** [comment]
@b-butler and I discussed this offline, but there is an additional change that needs to be made in this PR as well. Currently, the logic for directives that's used to resolve directives in `FlowGroup._get_submission_directives` is not present in `FlowGroup._create_run_job_operations`. We could either add that logic there, or add it to `_resolve_directives`. We should be able to share as much as possible between run and submission.

**Comment by csadorf** [comment]
@vyasr Why did you close the issue?

**Comment by vyasr** [comment]
@csadorf this issue was closed by the resolution of #260.
