### ISSUE TITLE
Job Aggregation for Operations

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#266]
This is just to include in our issues, a link to the discussion for job aggregation from a closed pull request. All discussion has be had thus far in #52  

The general idea is to allow operations to operate on multiple jobs at once.

**Comment by vyasr** [comment]
I believe that the PR you want is #52, right?

**Comment by csadorf** [comment]
> I believe that the PR you want is #52, right?

I edited the first comment.

**Comment by b-butler** [comment]
Yes it is. I just thought a link in our issues would be helpful to show the discussion thus far on the matter @vyasr.

**Comment by bdice** [comment]
Resolved by #464.
