### ISSUE TITLE
Add doc linting to CI

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#276]
### Feature description

Replicate glotzerlab/signac#294 for this repo. Pick some file as a starting point (we used jsondict.py in signac) and go from there.

### Proposed solution

Use pydocstyle as described in the corresponding signac issue.

**Comment by kidrahahjo** [comment]
@vyasr I'd like to work on this one, can you please assign me this?

**Comment by vyasr** [comment]
Sure! @kidrahahjo have a close look at glotzerlab/signac#294, it should provide the exact blueprint for what you need. Similar to that one, you'll want to pick one file (preferably a smaller one, not something like flow/project.py) and apply pydocstyle to it. Let me know if you have any questions.
