### ISSUE TITLE
Convert all docstrings to numpy style

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#278]
As part of our overall docs overhaul (see glotzerlab/signac-docs#64), we want to convert our docstrings to numpy style (as decided in glotzerlab/signac-docs#74). The best automated tool I'm familiar with for this task is [pyment](https://github.com/dadadel/pyment). In addition to converting docstrings, it will also generate docstrings for functions, classes, etc that are missing docstrings entirely. However, the conversion will require significant manual review to ensure that all docstrings are converted correctly.

**Comment by vyasr** [comment]
@CryoZEUS could you comment on this issue so that I can assign you?

**Comment by CryoZEUS** [comment]
Yeah, I'd love to work on it.

**Comment by b-butler** [comment]
We should revisit this after GSoC. We will likely need someone else to move #316 to completion.

**Comment by bdice** [comment]
Resolved by #392.
