### ISSUE TITLE
Proposal for operation hooks

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#28]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/28) by Carl Simon Adorf (Bitbucket: [csadorf](https://bitbucket.org/csadorf), GitHub: [csadorf](https://github.com/csadorf)).**

----------------------------------------

# About

This is a proposal for a feature that would allow users to specify hook functions that are executed either before or after the execution of an operation.
The purpose is to simplify the execution of specific functions before and after the execution of a job-operation, such as logging or data upload functions.

A hook function takes an instance of `JobOperation` as first argument which allows to access the name of the operation, the job it operates on, the command, and optional execution directives.
For example:
```
#!python
def log_operation(op):
    log("Operation {} started.".format(op))
```

This log function could then be specified to be executed on operation start:
```
#!python

@Project.operation
@Project.hook.on_start(log_operation)
def hello(job):
    print('hello', job)
```

# API

Hooks are in general defined as lists of functions, as part of the `flow.hooks.Hooks` class.

- `on_start`: Executed *before* a operation is executed.
- `on_finish`: Executed *after* a operation has completed (with or without error).
- `on_success`: Executed *after* a operation has completed without error.
- `on_fail`: Executed *after* a operation has completed with error.

## Low-level API

The low-level API allows the installation of hooks on the project instance level *via* the manipulation of the `hooks` instance variable:
```
#!python
project = Project()
project.hooks.on_start.append(my_log_function)
```
And during the adding of operations, again, via a dictionary:
```
#!python
project.add_operation(
    name='hello',
    cmd='echo hello {job._id}',
    hooks={'on_start': [my_log_function]})
```

The hooks are executed in order of definition, where project-wide hooks are executed *prior* to operation-wide hooks.

## Decorator API

Alternatively, hooks can be installed *via* the decorator API:

```
#!python
from flow import hook

@Project.hook.on_start(log_operation)
def my_op(job):
    pass
```
Note, that the hooks are only executed if the operation is executed through the `FlowProject` interface.

## Configurational API

Finally, hooks can be installed directly in the signac configuration by specifying a function that installs the hooks during project initialization.

```
#!bash
# signac.rc

[flow]
hooks = my_hooks.install_hooks
```
The `hooks` config key is interpreted as list, multiple modules would be provided as a comma-separated list.
The `my_hooks` module must be directly importable and should have a `install_hooks()` function in the global namespace similar to this:
```
#!python
# my_hooks.py

def log_operation(op):
    log("Operation {} started.".format(op))

def install_hooks(project):
    project.hooks.on_start.append(log_operation)
    return project
```

The `install_hooks()` function should return the project argument so that we can use the following idiom: `install_hooks(Project()).main()`.

The default hook installation function is called *install_hooks* so in this case the following configuration would be equivalent:
```
#!bash
[flow]
hooks = my_hooks
```
As a final example, assuming that the `flow` package had a module that would install hooks for the automatic generation of *snapshots* after execution, it would likely be installed like this:
```
#!bash
[flow]
hooks = flow.snapshots
```

**Comment by bdice** [comment]
This is resolved by #508.
