### ISSUE TITLE
Status legend is missing some statuses

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#284]
### Description

The status legend printed currently only includes information from `FlowProject.ALIASES` (see [here](https://github.com/glotzerlab/signac-flow/blob/215b252bbda798d2fcb9f0b44917c4fd70e996c5/flow/project.py#L1906)), but there are other status that could be displayed since this is controlled by `_STATUS` (see [here](https://github.com/glotzerlab/signac-flow/blob/215b252bbda798d2fcb9f0b44917c4fd70e996c5/flow/project.py#L3713) and [here](https://github.com/glotzerlab/signac-flow/blob/215b252bbda798d2fcb9f0b44917c4fd70e996c5/flow/project.py#L1944), where the latter is then used when formatting the jinja template). 

@zhou-pj you did a lot of work on refactoring the status rendering, is there any reason that the `ALIASES` and the `_FMT_SCHEDULER_STATUS` objects should be separate? Having a class member makes some sense in case there's a need to extend a FlowProject subclass to support a different set of status labels, but I'm not sure if these two variables are both necessary.

### To reproduce

Submit jobs to a scheduler and ideally put them on hold so they remain scheduled but not active. They will show up as [S] in the detailed view, but there is no legend entry for [S].

**Comment by zhou-pj** [comment]
Thanks for catching this! My guess is that they just got unsynced after a number of PRs. If I am not missing anything, the `ALIASES` should be mapped to the `_FMT_SCHEDULER_STATUS` and is solely used to form the legend. Right now I guess one more reason to keep them separate would be the new dummy status in `_FMT_SCHEDULER_STATUS`.

**Comment by zhou-pj** [comment]
I synced them in the PR above, if you think that would be sufficient. Otherwise we can discuss further improvements in the same PR.

**Comment by vyasr** [comment]
Resolved in #285.
