### ISSUE TITLE
Warning for requesting to run non-existent flow operation

### ISSUE THREAD

**Issue by rsdefever** [glotzerlab/signac-flow#291]
### Feature description

IMO it would be beneficial to throw a warning if a user requests to run a non-existent flow operation. Example, the flow operation is named `run_simulation` and the user types: `python project.py run -o run_simulations`. This would not execute the flow operation (it has a typo; `run_simulations` does not exist), and it would also not raise any warning or provide any other indication that nothing happened. 

### Proposed solution

A simple warning such as `The requested flow operation does not exist`.

**Comment by csadorf** [comment]
@rsdefever Thank you for the suggestion!

**Comment by bdice** [comment]
Resolved by #442.
