### ISSUE TITLE
Cannot see executable in pretend mode

### ISSUE THREAD

**Issue by tcmoore3** [glotzerlab/signac-flow#296]
### Description

The pretend mode in submit does not show the actual command that get called to run an operation. I think this is because it's showing the `run` command, but that does not show the user the executable that ultimately ends up being called (especially, e.g., if you're using a container).

### To reproduce

Here is what I see with pretend:

```
 $ python project.py submit -w 20 -b 2 -p --template great-lakes.sh --pretend
Using environment configuration: GreatLakesEnvironment
Query scheduler...
Fetching operation status: 100%|█████████████████████████████████████| 8/8 [00:00<00:00, 3274.88it/s]
Submitting cluster job 'projecte/bundle/d3dd91d2bdbc0d709054fa15b120b6c437df9741':
 - Group: sample(c0e5b2b05ec0b8b2355dea01193c22c2)
 - Group: sample(5e9ec3790f463a475257c0c96772e205)
WARNING:flow.project:Some of the keys provided as part of the directives were not used by the template script, including: nranks, omp_num_threads
#!/bin/bash
#SBATCH --job-name="project/bundle/d3dd91d2bdbc0d709054fa15b120b6c437df9741"
#SBATCH --partition=standard
#SBATCH --mem=4g
#SBATCH -t 20:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --account=acct_name

#SBATCH -o output-files/--parall-c0e5b2b05ec0b8b2355dea01193c22c2.o%j

set -e
set -u

cd /path/to/project
module load singularity
export CT=`date +%s`
export WT=72000
export HOOMD_WALLTIME_STOP=`echo "$CT+$WT-60" | bc`

# sample(c0e5b2b05ec0b8b2355dea01193c22c2)
/path/to/bin/python /path/to/project/project.py run -o sample -j c0e5b2b05ec0b8b2355dea01193c22c2 --parallel &

# sample(5e9ec3790f463a475257c0c96772e205)
/path/to/bin/python /path/to/project/project.py run -o sample -j 5e9ec3790f463a475257c0c96772e205 --parallel &

wait

```

I think because of the groups update, it's showing the run command, but this is misleading, especially since I am using a container and I want to ensure that the proper executable is being called. I decorated the operation with `@directives(executable='singularity exec software-greatlakes.simg python3')`, so it would be useful to be able to see that somewhere.

### System configuration

This is on Great Lakes. 

```
$ python -c 'import platform; print(platform.platform()); import sys; print(sys.version); import signac; print(signac.__version__); import flow; print(flow.__version__)'
Linux-3.10.0-1062.9.1.el7.x86_64-x86_64-with-glibc2.10
3.8.3 | packaged by conda-forge | (default, Jun  1 2020, 17:43:00) 
[GCC 7.5.0]
1.4.0
```

**Comment by bdice** [comment]
This is related to issue #252 and will be resolved by PR #279.

**Comment by csadorf** [comment]
Should we close issues if the related PR is not merged yet?

**Comment by bdice** [comment]
@csadorf Good point. I’ll reopen and mark #279 as resolving this. Initially I planned to close as a “duplicate” but then I changed my mind and decided it was “related” to #252.

**Comment by vyasr** [comment]
This issue is still not fully resolved, things like MPI prefixes are not yet visible in the pretend output and will need to be appended
