### ISSUE TITLE
Deprecate FlowCondition

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#307]
The FlowCondition class is currently part of the API, but there is no user-facing method that requires it or returns it, nor is there any reason for there to be one.

Moreover, I don't think there is a strong reason to maintain the class at all. It is a very thin wrapper around a callable, and converting to and from the class adds unnecessary overhead. We should change the `_prereqs` and `_postconds` of `FlowOperation` to directly store and use the callables. If desired, we can add the error handling of the callable in places where it's useful (which I think would be more readable in any case).

**Comment by csadorf** [comment]
Despite not being prefixed with `_`, this class was never intended to be user-facing, hence not listed in `__all__`. The class is hashable, handles some very basic logic when no callback is set, and raises a custom exception upon error that may be more informative than the standard exception. If you think that it is easier to implement this logic without this class, then I have no objections.
