### ISSUE TITLE
Make FlowOperation callable

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#308]
Currently the FlowOperations work differently than FlowCmdOperations. While the latter store their command internally and can be directly evaluated, the FlowOperations require lookup through the `_operation_functions` attribute of the FlowProject. We should change this and make FlowOperation callable and have it evaluate the operation function. Removing this indirection will centralize the logic for the execution directly in BaseFlowOperation and its subclasses, making it easier to modify for future changes since we won't have to check internally whether a given operation is a FlowOperation or a FlowCmdOperation.

**Comment by csadorf** [comment]
Generally in favor of making those two classes behave more similar / identical.

However, when I read the issue title I actually thought you meant that it would be possible to directly call a `FlowOperation` function like this:
```python
@Project.operation
def foo(job):
    print('hello', job)

if __name__ == '__main__':
    for job in project:
        foo(job)
```
But that's not what is meant here, is it?

**Comment by vyasr** [comment]
That's not exactly what I meant, although I did have that in mind when making this comment. The original motivation behind this issue was to remove the need for internal logic like this:
```
if isinstance(op, FlowCmdOperation):
    func = op._cmd
else:
    func = self._operation_functions[op_name]
```

However, we could introduce logic to make FlowCmdOperation directly executable. We would need to work out the semantics of the call operator to make sure they match well between the two types of operations, in particular perhaps making the call operator for FlowCmdOperation actually launch a subprocess and execute. In that case we would need to add a `get_cmd` method to get the command string for submit scripts etc. This would probably require moving the `cmd` decorator into the `operation` decorator namespace (like what's suggested in #309). If we did this, then we could make operations callable, in the sense of your example (where I assume that `foo(job)` would actually do things like check pre/post conditions as opposed to just calling the underlying function, which is what it would do right now).

**Comment by csadorf** [comment]
Sure, just make sure to not overload this issue too much, can be tackled later.

**Comment by b-butler** [comment]
I would keep it a thin wrapper for now (i.e. just call the internal function), and remove `FlowProject._operation_functions` (as it would be redundant at that point). Internally, though, we will need to do instance checks to ensure we handle the two classes correctly, because they will still behave differently as of now. I would recommend for any other thoughts on unification or change in behavior to be addressed in different issues and PRs.

Note: This isn't really different from what has been said, but I thought it was a useful summary.
