### ISSUE TITLE
Deprecate submit_operations and run_operations

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#310]
The `[submit|run]_operations` methods may not really need to be exposed. We should consider whether there are significant benefits to having both of these methods exposed in addition to the base `[submit|run]` methods. We've added a decent number of mechanisms by which the user can filter exactly what operations to run, and our proposals for aggregation will be adding additional selection protocols. If the primary benefit of supporting these two methods is to give users more direct control over exactly which operations run, I would suggest adding a comparable selection callable to be passed to `[submit|run]` so that users have more control over what is submitted. One other important reason to move in this direction is to reduce exposure of the `JobOperation` class to the user (although discussion of how far we can take that will be on a separate issue).

**Comment by csadorf** [comment]
If `JobOperation` is made private, then this function must be made private, agreed. I believe that this issue is so strongly coupled to #313  that it may be better to discuss this and implications as part of that issue and close this one.

**Comment by vyasr** [comment]
I wanted these as separate issues up front in case there was any argument for leaving `JobOperation` public while deprecating these methods. If not, then I agree that we should address all of this together.

**Comment by vyasr** [comment]
Closing in favor of #313
