### ISSUE TITLE
Deprecate the script command

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#311]
The `FlowProject.script` method is mostly redundant to `submit(pretend=True)`. The primary difference is that submit also includes the scheduler directives. @csadorf has previously argued that supporting this mode of getting a runnable script is important so that users could easily generate a submittable script, e.g. `python project.py script > run.sh`. I think that's a valid use, but it's one we could support by adding an extra argument `no_header` or similar to submit, and all we would have to do is ignore the environment (submitting on the `StandardEnvironment` is equivalent to `script` I believe).

**Comment by csadorf** [comment]
I don't think this is a really heavy used function, but I also don't quite see the point of deprecating it. If it is that easy to just use the `StandardEnvironment` in combination with `pretend=True`, why not leave this very thin wrapper function in place?

**Comment by vyasr** [comment]
Actually I think what would be the most helpful is to unify `script` with `_generate_submit_script`. We can leave `script` as part of the API and just extend its arguments to account for both use-cases. With this change we should be able to unify the upstream logic as well with respect to `_main_script` and `_main_submit(pretend=True)`. So only an internal refactoring, no need to change user APIs (except adding a few extra optional arguments to `script`).

**Comment by vyasr** [comment]
In light of #313, we are reverting to the original plan of deprecating the script command since the `JobOperation` class is being removed. However, as discussed above, re-enabling the same behavior using something like an underlying call to `_generate_submit_script` with a `StandardEnvironment` remains an option in the future version of the API.

**Comment by vyasr** [comment]
@csadorf @bdice do we still want to bother supporting the command line script interface now that we're removing the Python functionality? If we want to, I outlined the path forward above (have it call `_generate_submit_script` with the necessary environment mocking.

**Comment by csadorf** [comment]
> @csadorf @bdice do we still want to bother supporting the command line script interface now that we're removing the Python functionality? If we want to, I outlined the path forward above (have it call `_generate_submit_script` with the necessary environment mocking.

I always thought it was kind of nice to check the scripts using this command, on the other hand, one would want to use `run` anyways in a non-cluster/scheduler environment, so there is not much of a point. I also think that `run --pretend` can server the purpose of checking commands. So probably fine to drop this.

**Comment by bdice** [comment]
I always use `--pretend` and prefer that approach over the `script` command. I support deprecation.

**Comment by csadorf** [comment]
Looks like it is decided to deprecate.
