### ISSUE TITLE
Pin pytest, remove pytest-subtests plugin

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#332]
### Feature description

As reported in #330, `pytest-subtests` breaks and is often incompatible with brand-new releases of `pytest` (this has happened at least twice recently, to my knowledge). We should remove the dependence on `pytest-subtests`, which was primarily intended to be an intermediate-term solution to simplify our transition to `pytest`.

### Proposed solution

Refactor tests using `pytest-subtests`, remove the dependency, and pin `pytest` to the latest version in `requirements-test.txt`.

**Comment by kidrahahjo** [comment]
@bdice I'll try to refactor after GSoC gets over if it's not that urgent.

**Comment by bdice** [comment]
Resolved by #365.
