### ISSUE TITLE
Slow command line operations on macOS traced to external function in environment detection

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac-flow#339]
## Takeaway

This isn&rsquo;t a problem with signac-flow, but we could mitigate it by calling `socket.get_fqdn()` less. [ Jump to workaround.](#orgbc1f967)

<a id="orga8dc9b5"></a>

## Problem

On a newly created signac project, calls to `project.py [run | status | ...]` were taking at least 25 seconds to run.

I profiled the code by running `python -m cProfile -o out.prof project.py status` and found that the function `socket.getfqdn()` (get fully qualified domain name) was the root cause. It&rsquo;s called 5 times as part of `ComputeEnvironment.is_present()`, once each for each defined environment, as part of automatic environment determination in `get_environment()`.

I isolated this issue with:

    $ time python -c 'import socket; print(socket.getfqdn())'
    
    myComputerName.local
    
    real	0m5.050s
    user	0m0.029s
    sys	0m0.011s

The problem has been documented [on Stack Exchange](https://apple.stackexchange.com/questions/175320/why-is-my-hostname-resolution-taking-so-long) and could be related to [this Python bug report](https://bugs.python.org/issue35164#msg359718).

I&rsquo;m on macOS 10.14.6 running signac 1.4.0, flow 0.10.0 and Python 3.7.3.

<a id="org3bdee4e"></a>

## Attempted solution failed

I had the problem where the output of `scutil --get HostName` returned  `HostName: not set`. Note that the command `hostname` worked normally. Since LocalHostName was set, I followed the recommend procedure to fix this with `scutil --set HostName $(scutil --get LocalHostName)`. This command produced the expected result, but `getfqdn()` was still slow.

<a id="orgbc1f967"></a>

## Workaround

Since `get_environment()` checks environment variables before checking for the fully qualified domain name, I set the environment variable `SIGNAC_FLOW_ENVIRONMENT` to StandardEnvironment using

    export SIGNAC_FLOW_ENVIRONMENT=StandardEnvironment

<a id="orgacdb037"></a>

## Possible mitigations

1.  We could mitigate this issue by storing the output of `socket.getfqdn()`, so it wouldn&rsquo;t have to be called 5 or more times.

2.  Just like we have a warning for labels that take a long time to evaluate, perhaps we could time the call to `getfqdn()` and point users to this issue if it takes more than 1 s.

**Comment by csadorf** [comment]
Oh wow, I had no idea this function could cause problems like that. Suggestion: Wrap the call within a private method and cache the return value of `socket.getfqdn()` in a global (module) variable. The return value of this function is not expected to change over the lifetime of one session.

**Comment by csadorf** [comment]
Also, @cbkerr are you aware of the built-in profiling option for status? If yes, was that helpful?

**Comment by b-butler** [comment]
@cbkerr are you able to provide a PR to fix this? Simon's solution should work, and is what I thought to do as well.

**Comment by cbkerr** [comment]
@csadorf I didn't know about the built in profiler. Let's add it to the documentation!

@b-butler sure, I can work on this.

**Comment by bdice** [comment]
@cbkerr Would you like help implementing this change? We'd be happy to have a contribution to fix it.

**Comment by cbkerr** [comment]
Thanks for the ping @bdice. I tried implementing this change in #394 and would appreciate corrections to what is apparent of my understanding of python modules.
