### ISSUE TITLE
Bundle submission fails due to "/" in job name. Related to #224.

### ISSUE THREAD

**Issue by rsdefever** [glotzerlab/signac-flow#343]
Related to #224 .

### Description

I thought this issue had been fixed, but when bundling jobs the issue persists. It is fixed if signac jobs are submitted as individual cluster jobs.

### To reproduce

I am using the new "JOB_ID_SEPARATOR" option to specify that job names should use `-` rather than `/`. 

```
class NotreDameCRC(flow.environment.StandardEnvironment):

    hostname_pattern = r'.*\.crc\.nd\.edu$'
    template = 'crc.nd.sh'
    scheduler_type = SGEScheduler
    JOB_ID_SEPARATOR = '-'
```

However, when bundling:

```
$ python project.py submit --test --bundle=12
Using environment configuration: NotreDameCRC
Submitting cluster job 'equation-of-state/bundle/9aeb3d936021dad70ada14c313c8d8abc1aaa6fe':
 - Group: convert_volume_to_nm(ea8392fd562c3191ec7b86660edf77ca)
 - Group: convert_volume_to_nm(1e07ba71a6df8c0228e065a7e589e93b)
 - Group: convert_volume_to_nm(302f7b265c301e868b9a2de429d4c502)
 - Group: convert_volume_to_nm(f51b463edfe247c19b5aa85bb504136b)
 - Group: convert_volume_to_nm(b06ecdacf20a5f3dd9f9084c07a0f1d3)
 - Group: convert_volume_to_nm(392f596a51294589882d563575e27140)
 - Group: convert_volume_to_nm(e329e7236a025d06ca40af61960b0dfa)
 - Group: calculate_volume(eef72d74f816f8fd059e3c01d912cdad)
 - Group: calculate_volume(b009f84f0b5e73290c150c1df74107b5)
 - Group: calculate_volume(121a23057c5c190c42df207c130f629f)
 - Group: calculate_volume(aab2c7be210be75c8e0c2d2794472a77)
 - Group: calculate_volume(f4daae4ee403a129bd3b2c6d4eee3a76)
WARNING:flow.project:Some of the keys provided as part of the directives were not used by the template script, including: ngpu
#!/bin/bash
#$ -N equation-of-state/bundle/9aeb3d936021dad70ada14c313c8d8abc1aaa6fe
#$ -pe smp 1
#$ -r n
#$ -m ae

```

You can see the job name still has a `/` character in it.

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux
 - Version of Python [e.g. 3.7]: 3.8.5
 - Version of signac [e.g. 1.0]: 1.4.0
 - Version of signac-flow: 0.10.0

**Comment by csadorf** [comment]
Ah, shoot, we are using hard-coded `/` for bundled submissions: https://github.com/glotzerlab/signac-flow/blob/a2a95e788df1acbc5360850fa7012822c74ec7a7/flow/project.py#L1690

@glotzerlab/signac-developers Let's try to get a hotfix out for this asap.

**Comment by csadorf** [comment]
@rsdefever Would you be able to verify that #344 fixes the issue?

**Comment by rsdefever** [comment]
@csadorf I verified the fix. It works now! Thanks for the quick turnaround :D

**Comment by csadorf** [comment]
> @csadorf I verified the fix. It works now! Thanks for the quick turnaround :D

Great, thx for verifying. I'll push for a hotfix release as soon as possible.

**Comment by mikemhenry** [comment]
Before we close this bug, we should add a test for this behavior.

**Comment by csadorf** [comment]
> Before we close this bug, we should add a test for this behavior.

I won't have time to implement one, so if you or anybody else wants to give this a shot, you are very welcome.

**Comment by csadorf** [comment]
> > Before we close this bug, we should add a test for this behavior.
> 
> I won't have time to implement one, so if you or anybody else wants to give this a shot, you are very welcome.

I went ahead and did it. ;)
