### ISSUE TITLE
Make FlowProject Picklable

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#369]
### Feature description
We could make `FlowProject` picklable. This would likely simplify the parallelization logic to some extent. It would also be nice to make other `flow` objects picklable, but given our use of lambdas and other constructs may prove to be overly difficult for any easy in parallelization it brought.

### Proposed solution

`__getstate__` and `__setstate__` methods would need to be added to the `FlowProject`.

**Comment by kidrahahjo** [comment]
I'll start working on this.

**Comment by kidrahahjo** [comment]
This should be closed now!
