### ISSUE TITLE
Enable condition-override from the command line

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#38]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/38) by Jens Glaser (Bitbucket: [jens_glaser](https://bitbucket.org/jens_glaser), GitHub: [jglaser](https://github.com/jglaser)).**

----------------------------------------

Or alternatively, `--run` should allow to force operation execution even if the `post` condition is already fulfilled.

**Comment by csadorf** [comment]
The `exec` command is meant to not have any logic, I therefore suggest that we enable the `run` command to override conditions. We could add three switches `--ignore-conditions`, --ignore-pre-conditions`, `--ignore-post-conditions`. In fact, these options could be universal for `script`, `run`, and `submit`.

**Comment by csadorf** [comment]
@alacour Are you still working on this?

**Comment by alacour** [comment]
No, I am not working on it

**Comment by zhou-pj** [comment]
issue addressed in PR #209
