### ISSUE TITLE
Refactoring tasks

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#395]
### Feature description

While working on #387, #389, #392, I took some notes on APIs that could be easily removed/refactored on `next` after those PRs are merged. My notes are copied below. **I marked changes with ⚠️ that are API-breaking, but I don't think any of these changes would warrant a deprecation cycle.**

## Environments
`environment.py`
- [x] Make `ComputeEnvironmentType` private. Rename to `_ComputeEnvironmentType`. ⚠️

## Schedulers
`schedulers/base.py`
- [x] Make `Scheduler` into an abstract class (it is documented as an abstract class but doesn't inherit from `abc.ABC` or use `abc.abstractmethod`).
- [x] Add an abstract `submit` method to the `Scheduler` class.
`schedulers/fakescheduler.py`
- [x] The module `fakescheduler.py` should be renamed `fake_scheduler.py`. ⚠️
`schedulers/torque.py`
- [x] Torque scheduler should return True instead of a job id (I don't think the output is used, but this should be verified). ⚠️
`scheduling/status.py`
- [x] The whole file `scheduling/status.py` can be removed. It has one public method `update_status(job, scheduler_jobs)` that is unused / out-of-date, and the private methods are not used. (This is not API-breaking because it's been deprecated for so long)

In several modules:
- [x] Remove *args and **kwargs from all scheduler constructors (and submit methods if possible). ⚠️
- [x] Schedulers should return False instead of None if they fail (return type should always be `bool`). ⚠️
- [x] Order of arguments to submit (specifically `pretend` and `hold`) is not consistent across scheduler classes. These should all match. ⚠️

## Status rendering
`render_status.py`, `Renderer` class
- [x] The method `draw_progressbar` should be named `draw_progress_bar` (also update the names in the templates). ⚠️
- [x] `generate_terminal_output` and `generate_html_output` should be private. ⚠️
- [x] All the public instance variables like `Renderer.html_output` can be removed (not used). ⚠️ (this how now been made a private function instead of a public class)

## Templates
- [x] The "out" parameter can be removed from `template.py`'s `init` method, it isn't used. (If it would be helpful in writing tests, we should instead use an output redirection context manager.) ⚠️

## Utils
- [x] The "write_human_readable_statepoint" method has been deprecated since 0.6 and should be removed.

## Project
- [x] Consider deprecating `export_job_statuses`, I don't know if it's used anywhere, but it's not used internally and it's untested.

**Comment by shandave** [comment]
Hey @bdice, I'd like to contribute by deprecating the `export_job_statuses` method.

**Comment by vyasr** [comment]
Hi @shandave, welcome! We're happy to have you contribute. Feel free to reach out if you have questions about how to do this, we're available to provide guidance.

**Comment by bdice** [comment]
Welcome @shandave, thanks for reaching out! 😄 I recommend making a pull request with just one of the refactoring changes (the deprecation of `export_job_statuses`). 👍

**Comment by bdice** [comment]
Resolved by #426.
