### ISSUE TITLE
Remove "index" argument from scheduler job id generation.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#418]
Discussed with @b-butler @vyasr and @atravitz on Slack.
> Does anyone know what the `index` argument for submission operations is meant for? It is carried through FlowGroups, is used in the id generation, and is an parameter in creating submission/run operations but it appears to be 0 everywhere. It does not appear to be set to anything but 0 in the code, and I don't see any logic that increments its value. Is this legacy / can it be removed?

Summary of the conversation:
- This feature was introduced to resolve #18
- When #18 was addressed, we switched from just project name to project directory so that multiple projects with the same name could be submitted simultaneously.
- The feature has no clear utility at this point and may not even be fully implemented after the addition of groups and aggregation

There is a consensus that this argument should be removed.

**Comment by csadorf** [comment]
I originally introduced the index as a (premature?) generalization, should we ever support the submission of multiple copies of the same job. I am fine with simply removing it, since it seems to create a lot of confusion.

**Comment by bdice** [comment]
Resolved by #423.
