### ISSUE TITLE
Remove --test option from "submit" CLI

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#419]
Discussed on Slack with @vyasr @atravitz.
> I am not convinced that the behavior of `submit --test` is implemented in a way that is logically consistent. The option is only in the CLI, not the Python API. Its documentation reads "Do not interact with the scheduler, implies `--pretend`."

Summary of the conversation:
- It is unclear whether "not interacting with the scheduler" should rely on the project document's cached status from previous scheduler states.
- "the expected use case was for testing during development, possibly in environments where the scheduler was unknown/unconfigured/problematic. also at some point when schedulers were interacted with more directly to generate submission scripts (pre-jinja) i don’t remember what kind of output you’d get from the [FakeScheduler], i.e. even if you didn’t get errors you might get something that cluttered the output. given that context, it probably assumes that no cached status would exist, or just doesn’t consider that possibility at all" -- @vyasr 
- If users wish to skip interacting with the scheduler, it is possible to use the `TestEnvironment` (which uses the `FakeScheduler`).
- We do not expose any mechanism to perform "real" (not pretend) submission unless the scheduler state is checked first. This is important for safety/correctness.
- This feature is no longer useful and should be removed.

**Comment by kidrahahjo** [comment]
I'll implement this!
