### ISSUE TITLE
Create new block in `slurm.sh`

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-flow#456]
I propose grouping these lines into a new block, nested inside the `header` block.

https://github.com/glotzerlab/signac-flow/blob/dbe89263b002df8389e5dfaab02b81d5fec253e8/flow/templates/slurm.sh#L3-L17

Use-case: allows inheriting these lines and changing just the `tasks` block.

**Comment by vyasr** [comment]
Resolved in #459.
