### ISSUE TITLE
Add `before_operations` block to `base_script.sh`

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-flow#457]
I propose adding an empty block, `before_operations`, right after the `for` loop. 

https://github.com/glotzerlab/signac-flow/blob/dbe89263b002df8389e5dfaab02b81d5fec253e8/flow/templates/base_script.sh#L18-L20

Use case: `export CUDA_VISIBLE_DEVICES`, see https://github.com/glotzerlab/signac-flow/issues/455.

**Comment by vyasr** [comment]
Resolved in #458.
