### ISSUE TITLE
Summit template always assumes --parallel when computing number of nodes

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#46]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/46) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

@jglaser found a bug in the Summit template, where the number of nodes is computing assuming `parallel == True`, even if the flag `--parallel` was not provided.

**Comment by csadorf** [comment]
@bdice Can you comment on the status of this issue?

**Comment by bdice** [comment]
I haven't looked at this recently. Maybe @jglaser would know since he has worked with the template more recently.

**Comment by csadorf** [comment]
Is this fixed with merge of #63 ?

**Comment by csadorf** [comment]
I'm closing this since I have not received any responses.
