### ISSUE TITLE
Old add_operation API is broken

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#479]
### Description

The `add_operation` method of creating new operations no longer seems to work.

### To reproduce

Create the project file below.

```
# project.py
from flow import FlowProject

class Project(FlowProject):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_operation(
            'hello', cmd='echo hello', pre=[], post=[])

if __name__ == "__main__":
    Project().main()
```

Then execute `python project.py run` on the command line.

### Error output

The run above should print hello. Instead, it does nothing.

Looking through the code, the issue first appears during the run sequence in `Project._generate_selected_aggregate_groups` where the variable `aggregate_stores` is empty. The reason is that `self._group_to_aggregate_store` is empty. The problem is that `Project._register_groups` does not add items to `self._group_to_aggregate_store` from `self._operations` (i.e. the singleton operations. @bdice, @kidrahahjo, and @b-butler have all worked on this part of the code recently, so if any of you have a sufficient recollection to know offhand whether just adding instance-level operations to the bidict would be a safe and sufficient solution, let me know.

Alternatively, I traced the problem to #335 (unsurprisingly) using a git bisect. Just from looking at the diff, the problem is that the change to `_register_groups` in #335 only affects groups registered to the class, and that the PR likely missed the corresponding changes necessary to register aggregates for groups that are only added to the instance.

I have some other reviews that need to get done first, but if nobody gets around to this by then I can dig a little deeper.

**Comment by csadorf** [comment]
A fix should probably contain a very basic unit tests that prevents a future introduction of this regression.

**Comment by csadorf** [comment]
Since this is breaking a basic function, we should probably release a hotfix for this.
