### ISSUE TITLE
--only-incomplete-operations sorts instead of filters

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac-flow#481]
### Description

Using the `--only-incomplete-operations` CLI argument should show the statuses of jobs with eligible operations. Currently, it just puts all the complete operations at the end of the list.

### To reproduce and error output

Please copy & paste the code that is triggering the issue into this section and describe the context and prior steps that lead to the problem with as much detail as possible.
![image](https://user-images.githubusercontent.com/31974495/112070416-fd14ca80-8b43-11eb-80b3-5a0936cac997.png)

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]:
 - Version of Python [e.g. 3.7]:
 - Version of signac [e.g. 1.0]: 1.6.0
 - Version of signac-flow: 0.13.0

**Comment by vyasr** [comment]
@kidrahahjo you mentioned wanting to help out with this, should I assign you?

**Comment by bdice** [comment]
I can reproduce this issue and am going to try to fix it today.
