### ISSUE TITLE
The flow.run() function was removed, but is still part of the docs

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#513]
The `flow.run()` function was removed in version [0.14](https://docs.signac.io/projects/flow/en/v0.14.0/changes.html#version-0-14), but is still [prominently featured](https://docs.signac.io/en/latest/operations.html#the-flow-run-interface) as part of the framework documentation.

**Comment by bdice** [comment]
@csadorf What do you suggest doing with this section? Simply remove the existing content? Try to re-work it as a way to introduce the FlowProject more slowly? (Just trying to make the issue actionable and I don’t want to make that decision on my own if you have ideas. It’s likely that this could be a good office hours project with a small amount of guidance.)

**Comment by csadorf** [comment]
I still like the general approach of introducing the general concept without using any of signac-flow functions from a didactic point of view. So I'd keep all of that and simply remove the `flow.run()` specific section while making sure that transitions are still intact.

Then, as a final step, I'd evaluate whether it might make sense to convert the section into a `_The FlowProject/Concept_` subsection.

**Comment by kidrahahjo** [comment]
I think this is now resolved and hence we can close this issue now!
