### ISSUE TITLE
Support job/aggregate abbreviations in the -j option

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#519]
### Feature description
Given the new feature `aggregation`, I noticed that I could not easily grab only the aggregates with running `project.py status -d`. We support selecting operations using `-o` which supports regex. I think we should support regex in job selection on the CLI. This matters much less in Python as filters and for loops generally more useful. This would help without aggregation as well. @bdice mentioned that he frequently likes to grab all jobs that start with some value in order to partition the data space. Furthermore this would allow grabbing single jobs by only a specifying a few characters with something like `^ef9d31`.

### Proposed solution

Just change the way we compute jobs for the `-j` argument.

**Comment by csadorf** [comment]
I don't think that supporting regular expressions for a primary key that consists of semi-random chracters makes sense. We already support the selection of individual jobs with an abbreviated id. If you want to (randomly) partition the data space you could use either `-n` and in case that this is not random enough, we could explicitly shuffle the order with something like `--order=shuffle` or so. @bdice would be interested in your opinion on this.

**Comment by b-butler** [comment]
@csadorf True, I forgot about the abbreviated id. I originally argued for either a flag for only showing data on aggregates (i.e. `./project.py status -d --only-aggregates`), or one for only showing jobs that start with a specific substring (e.g. `./project.py status -d -j 'agg-'`). @bdice advecated for a regex solution since it is more powerful with little if any meaningful performance difference from a simple `startswith` check.

**Comment by bdice** [comment]
I think it’s important that `-j` works with both job ids and aggregate ids — we shouldn’t distinguish between those on the command line API. I don’t especially care if the filter is performed via `startswith` or a regex match, but I would lean towards a regex because that’s how the operation filter `-o` works. If that breaks backwards compatibility with the behavior of `-j` (it might) then we can just use `startswith`.

**Comment by csadorf** [comment]
Ok, I did not consider aggregate-ids in my previous comment. In that sense it might make slightly more sense. That said, I want to stress that my opposition to enabling regex parsing here is not one based on concerns with the implementation or performance, but conceptually: The job-id is a primary index and *is a number*. It is presented as hexadecimal in base 16, but is still just a number. I don't think we would even consider enabling regex parsing of the job-id if it was in base 10. So I don't think we should do that for base 16 either.

**Comment by bdice** [comment]
@csadorf I think that’s a good argument for having different behavior between `-j` (startswith) and `-o` (regex).

**Comment by bdice** [comment]
I resolved this in #542 and added a test for an aggregate abbreviation.
