### ISSUE TITLE
Support an easy method for creating custom templates

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#520]
### Feature description
Talking to @atravitz and @tommy-waltmann, we decided that we would like to lower the barrier to creating custom templates or custom input into templates. We originally discussed using a CLI option; however, after discussing it with @bdice led to the idea of creating a command line subcommand that would create a `templates` directory in the project directory and a `templates/custom.sh` template that extends the detected environment.

A second proposal that came from this discussion is adding a new block in the templates that is empty for all templates to more easily way of adding lines to a template without changing existing functionality. This is also less error-prone since no default template would use this block and a user could not forget to call `{{ super() }}`.

### Proposed solution

Add a subcommand `./project.py template create`.

**Comment by vyasr** [comment]
This is consistent with discussions that @csadorf and I have had in the past about also making it easier to create custom environments using a command line tool.

**Comment by bdice** [comment]
I was imagining this as `flow template create`.

I forget, are the template search paths relative to `signac.rc` or `project.py`? I think it searches relative to `signac.rc`. It might not matter as long as the `FlowProject().main()` function can also locate the project directory (which we know is possible).

**Comment by vyasr** [comment]
Should be relative to `signac.rc`.

**Comment by b-butler** [comment]
I am fine with using `flow` instead of `project.py`. I wasn't really thinking of the `flow` command at the time.
