### ISSUE TITLE
Wrong dependency flag for GreatLakes (SLURM)

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac-flow#530]
### Description

The `--after` flag submits the wrong arguments for `sbatch` on GreatLakes.

### To reproduce

```bash
>>> python flowproject/project.py submit -o <operation> <other flags> --after <SLURM job id>
Using environment configuration: GreatLakesEnvironment
Querying scheduler...
Submitting cluster job '<project>/<job id>/<operation>/<some hash>':
 - Group: <operation>(<job id>)
```

This submits correctly with:
```bash
>>> python flowproject/project.py submit -o <operation> <other flags> -- -d afterany:<SLURM job id>
Using environment configuration: GreatLakesEnvironment
Querying scheduler...
Submitting cluster job '<project>/<job id>/<operation>/<some hash>':
 - Group: <operation>(<job id>)
```
In the [slurm docs](https://slurm.schedmd.com/sbatch.html), it looks like the flag should be `--dependency` or `-d`, but it looks like we're submitting `depend`.

### Error output

```bash
Submission error: Error when calling submission command sbatch <other flags> depend="afterany:20979989":
sbatch: error: Unable to open file depend="afterany:20979989"

Execute with '--show-traceback' or '--debug' to get more information.
```
### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: CentOS Linux 7 (Core)
 - Version of Python [e.g. 3.7]: 3.9.1
 - Version of signac [e.g. 1.0]: 1.6.0
 - Version of signac-flow: 0.13.0

**Comment by bdice** [comment]
@klywang Good find. It should only require a fix to this line: https://github.com/glotzerlab/signac-flow/blob/156fa79d72a62c17ce4b350eb839875de2ddf0d2/flow/scheduling/slurm.py#L144
