### ISSUE TITLE
FlowProject.run() does not work when called from a python scripts in flow versions > 0.9.0

### ISSUE THREAD

**Issue by klywang** [glotzerlab/signac-flow#570]
### Description

@gaofy95 ran into this issue after upgrading `flow` on Summit. The error is triggered by the following line of code in [`_create_run_job_operations`](https://github.com/glotzerlab/signac-flow/blob/5605feffcf8f3127857cd5ec55434c3640ef761b/flow/project.py#L1086):

https://github.com/glotzerlab/signac-flow/blob/5605feffcf8f3127857cd5ec55434c3640ef761b/flow/project.py#L1121

When `FlowProject.run()` is called in a python script in `flow` versions > 0.9.0 fails because `jobs[0]._project` is type `signac.contirb.project.Project`. When an operation is run from the command or through a bash script (i.e. `project.py run`), `jobs[0]._project` is the correct type, `__main__.Project`.

### To reproduce

```python
import signac
import flow

class Project(flow.FlowProject):
    pass

@Project.operation
def foo(job):
    pass


if __name__ == "__main__":
    flow_project = Project()
    project = signac.get_project()
    job = project.open_job(statepoint={'a' : 0})  # or whatever statepoint/job id
    flow_project.run(jobs=[job])
```

### Error output

```bash
Traceback (most recent call last):
  File "/path/to/script/tmp/minimal_script.py", line 16, in <module>
    flow_project.run(jobs=[job])
  File "/path/to/signac-flow/flow/project.py", line 3348, in run
    operations.extend(
  File "/path/to/signac-flow/flow/project.py", line 1122, in _create_run_job_operations
    env = jobs[0]._project._environment
```
### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Ubuntu and  Red Hat Enterprise Linux (RHEL) version 8.2
 - Version of Python [e.g. 3.7]: 3.9.0 (for me) and (will update with version on Summit)
 - Version of signac [e.g. 1.0]: 1.5.1
 - Version of signac-flow: 0.10.0 and 0.16.0

**Comment by b-butler** [comment]
The problem is in

```python
project = signac.get_project()
job = project.open_job(statepoint={"a": 0})
```
A `FlowProject` is a signac `Project`. Thus, the solution is to use
```python
job = flow_project.open_job(statepoint={"a": 0})
```
Please close the issue if it solves your problem as I think it should @gaofy95 @klywang.

**Comment by klywang** [comment]
Thanks @b-butler!

**Comment by bdice** [comment]
This is a problem I’ve seen come up before. We could check `isinstance(job._project, FlowProject)` and raise a `ValueError` in functions that refer to that. Or perhaps try to open the job with the current FlowProject before raising the error?

**Comment by klywang** [comment]
@bdice So in the second option (try to open the job with the current `FlowProject` before raising the error), do something like `self.open_job(id=job.id)` first?

Also we should probably include this in the framework documentation. Unless you carefully read the API docs, it's not obvious to the user that you can use `FlowProject` to do all the same things you can do with a `signac` project. Maybe we should advise against switching back and forth between `signac` and `flow` in the docs?

**Comment by bdice** [comment]
@klywang Yeah, roughly this:
```python
def _get_FlowProject_job(job):
    if not isinstance(job._project, FlowProject):
        try:
            job = self.open_job(id=job.id)
        except LookupError: # is this right?
            raise ValueError("stuff")
    return job

jobs = [_get_FlowProject_job(job) for job in jobs]
```
