### ISSUE TITLE
@flow.cmd operations should raise `UserOperationError` like Python operations.

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#571]
It looks like the execution logic for `run` will raise `UserOperationError` if a Python operation fails, but not a `@flow.cmd` operation.

_Originally posted by @bdice in https://github.com/glotzerlab/signac-flow/pull/508#r696881917_

**Comment by kidrahahjo** [comment]
@bdice I have a question regarding this. Currently, `UserOperationError` doesn't show up on the upfront.

For example, for the operation
```python
def op(job):
    raise Exception
```

We would only show `UserOperationError` in the traceback and not in the main error message. The behaviour is perfectly fine, just wanted to ask if that's what we intend to do?

**Comment by vyasr** [comment]
That seems backwards to me. I think we'd want to show a `UserOperationError` up front and only show the `Exception` if the user does ` --show-traceback` or `--debug`.
