### ISSUE TITLE
single string names input won't be auto detected in project.submit()

### ISSUE THREAD

**Issue by zhou-pj** [glotzerlab/signac-flow#58]
### Description

When submitting jobs with python interface using project.submit(), and the names input is only one single string rather than list, submit won't auto detect single string and won't submit any job.

### To reproduce

project.submit(names='operation_name',...) 
won't submit any jobs as compare to

project.submit(names=['operation_name'],...) 

### System configuration

 - Operating System [stampede2]:
 - Version of Python [3.7]:
 - Version of signac [0.9.5]:
 - Version of signac-flow [0.6.4]:

**Comment by csadorf** [comment]
@zhou-pj I've created a patch that detects the bad `names` argument and raises an exception: See pull request #66.

**Comment by csadorf** [comment]
Resolved with merge of #66 .
