### ISSUE TITLE
Refine naming of hooks

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac-flow#612]
### Description

@klywang and I had some unresolved questions from our early drafts of the hooks documentation about what to call the hooks. We want to clarify the naming as follows:

1. rename `on_finish` to `on_exit` because we describe it that way in the draft docs ("will execute when the operation exits, with or without error").
2. rename `on_fail` to `on_error` because it better captures what the code is looking for.

Since we never released documentation on this (!), I expect it to be minimally disruptive. However, since this is a breaking change, we should go through a deprecation cycle

**Comment by cbkerr** [comment]
Discussed at the dev meeting today with Kelly, Simon, Brandon, Mike, and Vyas.

We decided on the following names:
- `on_start`
- `on_finish` --> `on_exit` (also considered "on_end")
- `on_success`
- `on_fail` --> `on_exception` (also considered "on_failure")

Note that as of now, 3/4 are related to the end of an operation.

Guidelines for future hooks to be noted in code comments
- use nouns

**Comment by bdice** [comment]
I would be okay with doing this name change without a deprecation cycle for simplicity. It's not a core API, has no docs, few (or no) users, and is likely to only affect power users who are involved with signac development.

**Comment by vyasr** [comment]
Yeah I'd say skip deprecation.

**Comment by kidrahahjo** [comment]
I think a quick fix for this would be:
1. Rename all instances of `on_finish` to `on_exit` and `on_fail` to `on_error`.
2. Update the changelog entry.
