### ISSUE TITLE
Need to update tests to avoid providing a signac project name 

### ISSUE THREAD

**Issue by cbkerr** [glotzerlab/signac-flow#613]
### Description

Tests still provided a project name after it was removed in glotzerlab/signac/pull/677

### To reproduce

Unit tests failed

### Error output

https://app.circleci.com/pipelines/github/glotzerlab/signac-flow/3353/workflows/0189a04d-015a-48d3-9da8-86a9b6317d09/jobs/20119

**Comment by vyasr** [comment]
Are you trying to use signac's `next` branch with signac-flow? Right now I would expect that to break _a lot_ of things, and we don't plan to update signac-flow until we're much closer to merging `next` into `master`.

**Comment by bdice** [comment]
We have a CI config that tests signac-flow with signac's `next` branch. Maybe we should disable it if we don't plan to keep signac-flow up to date until we're closer to releasing 2.0. https://github.com/glotzerlab/signac-flow/blob/1156bdc14b21fd45912415dd08b86f85af48543a/.circleci/config.yml#L99-L103

**Comment by vyasr** [comment]
We probably should, I don't think it makes a ton of sense to try and keep up flow regularly up to date with breaking changes. I think once we're close to a 2.0 release updating flow would be a good way to make sure that our changelog entry is complete and all breaking changes are properly listed though.

On a related note, we should probably update flow's version pinnings to be signac < 2.0. We know that current versions of flow will not work with new signac since (at minimum) the project name is removed.

**Comment by bdice** [comment]
If we add such a `<2.0` pinning, it will only make package solvers prefer signac-flow 0.18 (or whatever the last released version is before introducing that pinning). I have concerns that it would introduce more pain than it might solve.

> We’ll see it again, but just to point it out here: solver errors are pure evil, and can’t be fixed downstream. If a library requires `pyparsing>=3` and another library requests `pyparsing<3`, that’s the end, you are out of business. “Smart” solvers may look for older versions of those libraries to see if one exists that does not have that cap - if the one with the high lower bound had a release with a lower upper bound, that’s what it will choose; regardless of what bugs have been fixed, etc. since that release. We’ll discuss the problems this causes later. However, an under-constrained build is completely trivial to fix for any user. It’s just a minor inconvenience to a large number of users.

https://iscinumpy.dev/post/bound-version-constraints/

**Comment by bdice** [comment]
I opened https://github.com/glotzerlab/signac-flow/pull/616/ to stop running the tests for now. We'll come back to signac-flow compatibility later on, once the API for signac 2.0 is more stable.

**Comment by vyasr** [comment]
@bdice that's fair, in practice pinnings do cause a ton of problems. There's no way to "backport" those pinnings to all older versions, and even if you could that would only solve a subset of the issues. I don't think that it's really our responsibility to solve this problem for people installing anything other than the main branch from source, at that point you're very much in advanced user/developer territory, but it would be nice if there was something we could do for users installing via standard distribution mechanisms to warn them when they update signac that flow needs an update too.
