### ISSUE TITLE
Provide a local testing environment for signac-flow

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#625]
### Feature description

When I was working on aggregation, I used to test `flow` with a separate signac setup file. Sometimes changing directories gets frustrating, and now that I use `pyenv` for managing Python environments, I have set it up in such a way that the virtual environment deactivates when I move out of the directory. 

Can we provide some way to test flow locally? I understand that we have tests for the same reason but sometimes it's much easier to write a script for flow to test certain behaviours than writing tests. 

### Proposed solution
Asking users to test signac-flow in some directory, for example `localtesting/` where we simply provide them with 2 files, `init.py` (for generating signac projects) and `project.py` (to test the workflow). We can then simply ignore the `localtesting` directory by adding it to `.gitignore`.

**Comment by kidrahahjo** [comment]
I know this issue is more of a "me being lazy" issue than an actual issue with `flow`, so I'd completely understand if we end up not moving forward with this. 😂

**Comment by bdice** [comment]
@kidrahahjo Have you tried using `flow init` to generate a project? That is a quick way to test the project CLI.

**Comment by kidrahahjo** [comment]
Yup, I understand that, but after that when we add things to a branch using `git add` the `signac.rc` and `project.py` files may also get added to the repository sometimes. I propose providing a directory which we'll always ignore while adding things.

**Comment by kidrahahjo** [comment]
We can close this issue as of now because I also don't feel like introducing something in the repository just for local testing without any strong requirement.
