### ISSUE TITLE
Inconsistent tag format v.0.19.0

### ISSUE THREAD

**Issue by joaander** [glotzerlab/signac-flow#636]
### Description

The latest tag is `v.0.19.0`. This is inconsistent with earlier tag naming schemes which would name the tag `v0.19.0`.

Is the new naming scheme intentional? Should I expect the names to be "v.{semantic_version}" going forward?

### To reproduce

In the glotzerlab-software container builds, I have:
```
git clone --branch v$(python3 -c "import flow; print(flow.__version__)") --depth 1 https://github.com/glotzerlab/signac-flow.git
```

### Error output

```
warning: Could not find remote branch v0.19.0 to clone
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Linux
 - Version of Python [e.g. 3.7]: 3.9
 - Version of signac-flow: 0.19.0

**Comment by bdice** [comment]
cc: v0.19.0 release manager @cbkerr 

I deleted tag `v.0.19.0` and pushed tag `v0.19.0` following [these instructions](https://stackoverflow.com/a/5719854/). This should fix the issue reported here and should also help conda-forge detect the new release. Developers with the local tag `v.0.19.0` should run `git pull --prune --tags`.

**Comment by bdice** [comment]
I also moved the release to point to the corrected tag. https://github.com/glotzerlab/signac-flow/releases/tag/v0.19.0
