### ISSUE TITLE
Aggregation breaks project serialization for parallel execution

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#642]
### Description
Using `@aggregator()` breaks project serialization. This prevents users from running commands in parallel, like `python project.py run -o my_operation --parallel`. This breaks all operations, even if the operation being run is not an aggregate operation. Discovered by @jdice.

### To reproduce

```python
import cloudpickle
import signac
from flow import FlowProject, aggregator


@aggregator()
@FlowProject.operation
def agg_op(*jobs):
    pass


if __name__ == "__main__":
    pr = signac.init_project("test")
    pr.open_job({"a": 1}).init()

    pr = FlowProject()
    pkl = cloudpickle.dumps(pr)
    cloudpickle.loads(pkl)
```

### Error output

```pytb
Traceback (most recent call last):
  File "/home/bdice/tmp_signac/project.py", line 18, in <module>
    cloudpickle.loads(pkl)
  File "/home/bdice/code/signac/signac/contrib/job.py", line 941, in __setstate__
    self.statepoint._jobs.append(self)
  File "/home/bdice/code/signac/signac/contrib/job.py", line 476, in statepoint
    jobs=[self], filename=self._statepoint_filename
  File "/home/bdice/code/signac/signac/contrib/job.py", line 360, in _statepoint_filename
    return os.sep.join((self.workspace(), self.FN_MANIFEST))
  File "/home/bdice/code/signac/signac/contrib/job.py", line 352, in workspace
    self._wd = os.sep.join((self._project.workspace(), self.id))
  File "/home/bdice/code/signac/signac/contrib/project.py", line 379, in workspace
    if self._wd is None:
AttributeError: 'FlowProject' object has no attribute '_wd'
```

### System configuration

 - Version of Python: 3.9 
 - Version of signac: 1.7.0 (development version)
 - Version of signac-flow: 0.19.0 (development version)
 - Version of cloudpickle: 2.0.0. I also confirmed this is broken in cloudpickle 1.6.0.

**Comment by kidrahahjo** [comment]
@bdice I think it's a problem with the pickling of the `_AggregateStore` object. It's probably caused because aggregate information is generated for every operation/group regardless of the operations requested by the user.

**Comment by bdice** [comment]
@kidrahahjo Yes, that sounds possible. I believe it only happens if an operation acting on aggregates is in the project.
