### ISSUE TITLE
Finding the correct usage of the parser argument in FlowProject.main, extending subcommands

### ISSUE THREAD

**Issue by ianrgraham** [glotzerlab/signac-flow#648]
### Feature description

I was interested in extending some of the subcommands that `FlowProjects.main` implements by providing my own parser. In particular, I wanted to add commands to initialize and clear the statepoints of a workspace (and later other things I'd like to automate in a derived class). My initial idea was something like this ...

``` python
class Project(flow.FlowProject):

    def _main_init(self):
        
        project = self
        
        if "initialized" not in project.doc:
            print("Initializing project")
            project.doc["initialized"] = True
        else:
            raise RuntimeError("Project has already been initialized")

        if "cur_seed" not in project.doc:
            project.doc["cur_seed"] = 0

        # Initialize the data space
        statepoint_grid = {
            "it": range(5), 
            "phi": [1.0, 1.1, 1.2, 1.3]
        }

        for sp in grid(statepoint_grid):
            job = project.open_job(sp).init()
            if "init" not in job.doc:
                job.document["seed"] = project.doc["cur_seed"]
                job.document['init'] = True
                project.doc["cur_seed"] += 1

    def _main_clear(self):
        safe_clean_signac_project(self.root_directory())

    def main(self):

        parser = argparse.ArgumentParser()
        subparsers = parser.add_subparsers()

        # init subcommand
        parser_init = subparsers.add_parser(
            "inits",
            description="Initialize state points.",
        )
        parser_init.set_defaults(func=self._main_init)

        # clear subcommand
        parser_clear = subparsers.add_parser(
            "clear",
            description="Clear current state points",
        )
        parser_clear.set_defaults(func=self._main_clear)

        super().main(parser=parser)
```

Though this leads to the following error message

``` bash
usage: my-script.py [-h] [-v] [--show-traceback] [--debug] {inits,clear} ...
my-script.py: error: cannot have multiple subparser arguments
```

because another `subparsers` object is created in `FlowProjects.main`. But there are other problems with this solution, including the shared arguments (verbose, show-traceback, and debug) that must be defined for the new subparsers as well.

This is a pretty inelegant solution, but I was able to shoehorn my subcommands into the parser by refactoring the main function to accept a parser, subparser, and even a base_parser.

``` python
# ---------- my-script.py ----------
class Project(flow.FlowProject):

    # other methods

    def main(self):

        parser = argparse.ArgumentParser()
        base_parser = argparse.ArgumentParser(add_help=False)
        self._set_shared_args(parser, base_parser)

        subparsers = parser.add_subparsers()

        parser_init = subparsers.add_parser(
            "init",
            parents=[base_parser],
            description="Initialize statepoints for processing.",
        )
        parser_init.set_defaults(func=self._main_init)

        parser_clear = subparsers.add_parser(
            "clear",
            parents=[base_parser],
            description="Clear current state points",
        )
        parser_clear.set_defaults(func=self._main_clear)

        super().main(parser=parser, subparsers=subparsers, base_parser=base_parser)

# ---------- flow.project.py ----------
class FlowProject(signac.contrib.Project, metaclass=_FlowProjectClass):

    # other methods

    def _set_shared_args(self, parser, base_parser):
        # The argparse module does not automatically merge options shared between the main
        # parser and the subparsers. We therefore assign different destinations for each
        # option and then merge them manually below.
        for prefix, _parser in (("main_", parser), ("", base_parser)):
            _parser.add_argument(
                "-v",
                "--verbose",
                dest=prefix + "verbose",
                action="count",
                default=0,
                help="Increase output verbosity.",
            )
            _parser.add_argument(
                "--show-traceback",
                dest=prefix + "show_traceback",
                action="store_true",
                help="Show the full traceback on error.",
            )
            _parser.add_argument(
                "--debug",
                dest=prefix + "debug",
                action="store_true",
                help="This option implies `-vv --show-traceback`.",
            )

    def main(self, parser=None, subparsers=None, base_parser=None):
        """Docstring ... """
        self._entrypoint.setdefault(
            "path", os.path.realpath(inspect.stack()[-1].filename)
        )

        if parser is None:
            parser = argparse.ArgumentParser()
            if subparsers is None:
                subparsers = parser.add_subparsers()

        if base_parser is None:
            base_parser = argparse.ArgumentParser(add_help=False)
            self._set_shared_args(parser, base_parser)

        # everything else remains unchanged
```

This is in no way a nice solution, but it brings up the question of how I should be using the `parser` argument to `FlowProject.main`? It appears non-trivial to me to make any sort of complicated extension of the main function by feeding in a parser.

### Proposed solution

While trying to figure out how to do this, a nice idea for improving how `signac-flow` handles subcommands came to mind. Using `FlowProject.operation` as inspiration, it might be nice to introduce a wrapper-style function for subcommands? Something like ...

``` python
@Project.subcommand
def init(args):
    pass
```
The wrapper would just register the functions with the class, and then the functions would be hooked into the argument parser when `Project.main` is run. For arguments of subcommands, syntax could be borrowed from CLI libraries like [click](https://palletsprojects.com/p/click/). So in the end you could have something like ...

``` python
@Project.subcommand
@Project.option("--realizations", default=None, help="Number of realizations.")
@Project.option("--verbose", is_flag=True, help="Increase output verbosity.")
def init(realization, verbose):
    pass
```

This might be a cool functional addition to `signac-flow`.

**Comment by bdice** [comment]
@ianrgraham This is a really interesting and detailed writeup. To be honest, I haven't touched the CLI side of `signac-flow` very much, and my knowledge of `argparse` is somewhat incomplete. From a library design perspective, this proposal raises some questions for me. Primarily, I am unsure if the changes you're proposing are a good fit for the scope of `signac-flow`. It sounds like you would be far better served by creating a separate CLI in `click` (or another CLI builder) to perform whatever actions you had in mind.

> I wanted to add commands to initialize and clear the statepoints of a workspace

Some of these commands are already implemented in the core `signac` CLI! Generally, the creation and modification of a signac data space should be performed by the core `signac` package, rather than `signac-flow` which is meant for workflows. In the [`signac` CLI documentation](https://docs.signac.io/projects/core/en/latest/cli.html), there are commands like `signac job --create '{"key": "value"}'` that can create state points. Similarly, you can use `signac find` to locate job ids that match a filter and pipe those to `signac rm` to remove the matching jobs.

A more concrete demo of how to use the CLI to create / filter / remove jobs:

```bash
~ $ mkdir tmp_project
~ $ cd tmp_project
~/tmp_project $ signac init tmp_project
Initialized project 'tmp_project'.
~/tmp_project $ for i in $(seq 3); do signac job --create "{\"i\": $i}"; done
caaae429dd8b49a9d50e8104c82e3591
21df97087ecc1ed9e3660064418c50cb
812d32203b0c3520838c1602144d9521
~/tmp_project $ signac find i.\$gte 2
Interpreted filter arguments as '{"i.$gte": 2}'.
812d32203b0c3520838c1602144d9521
21df97087ecc1ed9e3660064418c50cb
~/tmp_project $ signac find i.\$gte 2 | xargs signac rm
Interpreted filter arguments as '{"i.$gte": 2}'.
~/tmp_project $ signac find
caaae429dd8b49a9d50e8104c82e3591
```

I really appreciate your creative approach to this! If you have more information about the exact problems you're trying to solve, feel free to share. I hope the existing signac CLI or a separate `click`-based script can be helpful to you. If there are features that you think would be a better fit for signac-flow's FlowProject CLI, that would also be helpful to hear.

**Comment by ianrgraham** [comment]
Thanks for the response! And sorry for my delayed reply! I think your point is well made; I don't have to use the FlowProject for all things regarding the workspace and can easily get away with keeping the logic for statepoint management in another script, in a jupyter notebook, as a preprocessor before `FlowProject.main` is called, or just from the terminal. Again, I appreciate your detailed response!
