### ISSUE TITLE
Use jinja2 templating for the status output formatting

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#67]
### Feature description

We should switch to using `jinja2` to format the status output. This would not only simplify the implementation, but would also allow users to design their own status output for individual projects.

### Proposed solution

Just like submission templates, there would be a default status template which can be replaced, extended by placing a `status.txt` file in a project's `templates/` directory.

**Comment by zhou-pj** [comment]
Start working on this issue now. Just want to make sure no one is also working on it.

**Comment by tcmoore3** [comment]
Resolved with PR #111
