### ISSUE TITLE
`flow.FlowProject.run()` does not accept jobs retrieved from `signac.Project()`.

### ISSUE THREAD

**Issue by d31v1vi5** [glotzerlab/signac-flow#753]
### Description

While trying to run a `FlowProject` only on a subset of jobs I have ran into an issue, where when I pass an at iterable of jobs (which I have retrieved by `open_job()` or `find_jobs()`) into `FlowProject.run()` an error occurs.

After a little digging I think that this is due to the fact that the `Job` object in contains a `_project` attribute that has a `Project` type from `signac` module and  `FlowProject.run()` expects it to be `FlowProject` type from `flow`. 

### To reproduce

Minimal example:

```
import signac
from flow import FlowProject


signac_project = signac.init_project()
job = signac_project.open_job({"foo": "foo"}).init()


class Project(FlowProject):
    pass


@Project.post.isfile('file.txt')
@Project.operation
def make_file(job):
    with job:
        with open('file.txt', 'w') as file:
            file.write("Test!")


Project().run([job])
```

### Error output

```
Traceback (most recent call last):
  File "/Users/dr/signac-tpb/misc/test.py", line 21, in <module>
    Project().run([job])
  File "/Users/dr/signac-tpb/external/signac-flow/flow/project.py", line 3693, in run
    operations.extend(
  File "/Users/dr/signac-tpb/external/signac-flow/flow/project.py", line 1132, in _create_run_job_operations
    env = jobs[0]._project._environment
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Project' object has no attribute '_environment'
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: macOS-13.4-arm64-arm-64bit
 - Version of Python [e.g. 3.7]: 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)]
 - Version of signac [e.g. 1.0]: 2.0.0
 - Version of signac-flow: 0.25.1

**Comment by b-butler** [comment]
Hey @d31v1vi5  sorry for the late response, can you try
```
import signac
from flow import FlowProject

class Project(FlowProject):
    pass


@Project.post.isfile('file.txt')
@Project.operation
def make_file(job):
    with job:
        with open('file.txt', 'w') as file:
            file.write("Test!")


signac_project = Project.init_project()
job = signac_project.open_job({"foo": "foo"}).init()
Project().run([job])
```

What you report is not a bug per-say just somewhat unintuitive behavior.

**Comment by d31v1vi5** [comment]
Hello, @b-butler. The code you suggested works. Thank you.

I don't recall the details, however there was a discussion as to why this is an undesired behaviour in the #support channel on Slack on the same date this issue was posted (Jun 13). If you have access please see it.

**Comment by b-butler** [comment]
As we do not have Slack premium, we can no longer access that conversation. I would be willing to here your case and the possible ways to implement it.

As I currently see it, given that `signac_project` and `Project` are two different objects and thus I wouldn't necessarily expect everything to just work with the `project` attribute. We could try to fix this by checking everywhere we use `job.project` and switch to requiring `project` be passed as well. However, I am not sure such a change is warranted.

**Comment by d31v1vi5** [comment]
I’ve expected that the `class Jobs` objects retrieved from `class Project` and `class FlowProject` are interchangeable as they are the instance of the same class, however it is not the case.

Personally, as a user, I would be happy with an error mesage which would say something along: “Jobs used by FlowProject methods must be retrieved from FlowProject”.

**Comment by b-butler** [comment]
@d31v1vi5, we could add a warning message of the sort. Is part of the unexpected nature, that it isn't clear in the documentation that `Job` instances belong to a specific `Project` instance and are not interchangeable?

**Comment by d31v1vi5** [comment]
Sorry for a delayed response.

I've glanced over the documentation, and was unable to find a place where this detail is mentioned explicitly. My thought was that since technically it's the same `Project`, as in represented by the same file structure, the `Job` instances are interchange.

**Comment by joaander** [comment]
The names are similar because `flow.FlowProject` _is a_ subclass of `signac.Project`. In your original script `signac.init_project` returns a `signac.Project` while `Project()` creates your subclass of `flow.FlowProject`. While these point to the same underlying file structure the `signac.Project` lacks methods and attributes that `flow.FlowProject` adds (such as `_environment`).

Here is a more minimal modification to your original script that uses an instance of `Project()` to create the job. It runs without error.
```python
import signac
from flow import FlowProject


class Project(FlowProject):
    pass


signac_project = Project()
job = signac_project.open_job({"foo": "foo"}).init()


@Project.post.isfile('file.txt')
@Project.operation
def make_file(job):
    with job:
        with open('file.txt', 'w') as file:
            file.write("Test!")


Project().run([job])
```
