### ISSUE TITLE
Error in cache generation

### ISSUE THREAD

**Issue by rosecers** [glotzerlab/signac-flow#96]
### Description

_status does not recompile, leading to an innaccurate status in "python project.py status -d"

### To reproduce

Please copy & paste the code that is triggering the issue into this section and describe the context and prior steps that lead to the problem with as much detail as possible.

### Error output

-bash-4.2$ python project.py status -d
Query scheduler...
Collect job status info: 100%|████████████████████████████████████████████████████████████████████████████████| 81/81 [00:00<00:00, 105.90it/s]
# Overview:
Total # of jobs: 81

label         ratio
------------  -------------------------------------------------
compressed    |######----------------------------------| 16.05%
equilibrated  |#####-----------------------------------| 14.81%
done_running  |#####-----------------------------------| 14.81%
33%           |----------------------------------------| 1.23%

# Detailed View:
job_id                            operation        labels
--------------------------------  ---------------  --------------------------------------
700a293e2df1e032346774d44f5656db  compress [Q]     compressed, done_running, equilibrated
112a67674c6bcb4ed05e7fde4a7b967b  compress [Q]     compressed, done_running, equilibrated
bf1c753e8613d4b2492934a161a59890  compress [Q]     compressed, done_running, equilibrated
ff97ee4663b0be773ed0618c21cfa4e6  compress    [Q]  33%, compressed
                                  equilibrate [U]  33%, compressed
a9d555ce79adf8a1a03bc5b018659177  compress [Q]     compressed, done_running, equilibrated
50fcf6c8bfbfab2cb38a1837ac66e3e6  compress [Q]     compressed, done_running, equilibrated
804162f005b6b1abe128433d3793555c  compress [Q]     compressed, done_running, equilibrated
a03ae81488e9bd448f3eb824197fc202  compress [Q]     compressed, done_running, equilibrated
b36ae53f16541b4d2ba38904e9c9b305  compress [Q]     compressed, done_running, equilibrated
d59f6d51947ad38e0206a359d19592db  compress [Q]     compressed, done_running, equilibrated
97980efe99f649a732fbdbc4dd43e011  compress [U]
6e2166d134315ceb66a6a7781209e1c7  compress [U]
afff6400f4810b9d5cefe11ac0b0d6b6  compress [U]
695d879f84174f5841cfc6004b32df0a  compress [U]
a2d829f4a59f60359748d2ddd76e7dde  compress [U]
4f629d96269b35ba83841555769875e5  compress [U]
8bf28f21e06d26c8e6b416061c396ee3  compress [U]
7c9185b1a53d109c00ed72cd97292259  compress [U]
06091f3668c9cbe6426711465a901849  compress [U]
45d83ad75c613e3632bb0d920836c8f7  compress [U]
1640a0124a15c2de2c6d1033c165b6db  compress [U]
33c087cc3db74316ff064a77bc448c92  compress [U]
c7b7f299dce7830f97783276eeae8637  compress [U]
dc53642d55de971612a96205edc3f67d  compress [U]
504f89ac60247812f65bad74f6f9488d  compress [U]
e3808b8fff7f05990eaba530f858ae1d  compress [U]
4b643e298d15c995b4814c69eca63946  compress [U]
51db1bd2e5688d0a09f674782c02375d  compress [U]
7b3d3c1239798ef52e8b09023bf8c774  compress [U]
fac69e47543941f005c8cad32beb2473  compress [U]
29819d790d19c7cf5ab73fd4588724a4  compress [U]
7e6f5719cd3dce9e97199b5880962420  compress [U]
eafa03a575e2a75fb2c92e137cf38267  equilibrate [A]  compressed, done_running, equilibrated
cdd9cbd03ffee053c08dafb33354b75b  equilibrate [A]  compressed, done_running, equilibrated
48034540f34427abfa049ec241ac337e  equilibrate [A]  compressed, done_running, equilibrated
[R]:registered [Q]:queued [!]:requires_attention [I]:inactive [U]:unknown [A]:active

### System configuration

Please complete the following information:

 - Operating System: Occuring on flux
 - Version of Python: Python 3.5.2
 - Version of signac: signac 1.0.0
 - Version of signac-flow: 0.7.0

Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.6.1810-Core
3.5.2 (default, Jul 12 2016, 17:04:24) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
1.0.0
0.7.0

**Comment by csadorf** [comment]
Fixed with merge of #97 .
